### ISSUE TITLE
添加http支持

### ISSUE THREAD

**Issue by iamCristYe** [Kyle-Kyle/baidudl#1]
pan.baidu.com现在并不会自动跳转https，因此希望添加这一扩展在http页面上的支持。

**Comment by Kyle-Kyle** [comment]
在我自己的电脑上以及大图的电脑上。pan.baidu.com都是https。不知道怎么样使用http。extension可以支持http。但我没法进行测试

**Comment by iamCristYe** [comment]
直接点开来就是http呀……你现在的代码不支持http的似乎

Best Regards,
Crist Xiaotian Ye

On May 16, 2017, at 23:09, Kyle Zeng <notifications@github.com<mailto:notifications@github.com>> wrote:


在我自己的电脑上以及大图的电脑上。pan.baidu.com<http://pan.baidu.com>都是https。不知道怎么样使用http。extension可以支持http。但我没法进行测试

**Comment by Kyle-Kyle** [comment]
直接点开？点开哪里。我点开全是https。改成http都会变成https

**Comment by Kyle-Kyle** [comment]
已添加http支持
