### ISSUE TITLE
添加中文README

### ISSUE THREAD

**Issue by sonichy** [Kyle-Kyle/baidudl#100]
1.百度是中国的产品，外国人不用的，中国人看着费劲，外国人又不看，何必呢，好用自然会给你上星。
2.能不能有点民族自豪感，用自己的语言写说明，让外国人来学中文。

**Comment by Kyle-Kyle** [comment]
并不。联系我的外国人用户和国人差不多多。
并且。写代码的时候我比较喜欢写英文。抱歉。
不过加一个中文说明确实是个不错的选择。

**Comment by Kyle-Kyle** [comment]
当然。从issue来看似乎确实国人多很多。

**Comment by sonichy** [comment]
列表链接是空的，还有，我只想下载某一个怎么办？

**Comment by sonichy** [comment]
[图片链接](http://sonichy.gitee.io/bddl.png)

**Comment by sonichy** [comment]
明白了，原来要勾选要generate要等待。
建议获取已勾选的项目，很多时候只想下载一项，哪有那么多带宽～

**Comment by Kyle-Kyle** [comment]
迅雷400KB当然很慢。这个项目有专门的下载器。还没优化好。平均速度3MB/s吧。使用方式的话...暂时没有详细教程。

**Comment by Kyle-Kyle** [comment]
哦。是有的。
Method2: RPC download
Step 1-3:
Same to Diretly download

Step 4:
Open up baidudl-rpc, or run aria2c-rpc

Step 5:
Click RPCdownload button

**Comment by Kyle-Kyle** [comment]
https://github.com/Kyle-Kyle/baidudl/blob/master/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md
