### ISSUE TITLE
RPC download 线程数

### ISSUE THREAD

**Issue by louislou123** [Kyle-Kyle/baidudl#101]
下载时使用RPC download，足足有80个线程，远远超过我aria2 config文件17个线程的限制。可能是因为线程数过多会不停触发百度的限制，下载速度一直在0-1.8mb/s之间波动，并可观察到在下降区间时尽管有速度但已下载大小不变。
![1](https://user-images.githubusercontent.com/20656759/40167664-732ddb10-5976-11e8-89a1-b91870cb3b66.jpeg)

**Comment by Kyle-Kyle** [comment]
好问题。现在的操作会覆盖掉aria2的config。

**Comment by Kyle-Kyle** [comment]
可以在config里面添加这个设置

**Comment by Kyle-Kyle** [comment]
已完成
