### ISSUE TITLE
Checksum error detected. 【奇怪问题】

### ISSUE THREAD

**Issue by qwertccc** [Kyle-Kyle/baidudl#102]
[Checksum:#506dd6 435MiB/440MiB(98%)]
05/18 10:28:13 [ERROR] Checksum error detected. file=D://Photoshop_CC_19.1.4_CHS_Lite_201805_X64.exe

05/18 10:28:13 [NOTICE] Download GID#506dd6f26989b73e not complete: D://Photoshop_CC_19.1.4_CHS_Lite_201805_X64.exe

同一文件连续下载了4次，每次都报这个错误，下载到本地的4个文件hash都一致

**Comment by qwertccc** [comment]
一会儿我找个本地独一无二的文件传上去再下来回来试试，如果报这个错误的情况下，本地原始文件和下载文件的hash是否一致

**Comment by Kyle-Kyle** [comment]
怀疑是没有获取到md5。是只有这个文件这样还是所有文件这样？之前有人汇报他的所有文件都这样。

**Comment by Kyle-Kyle** [comment]
如果可以的话可以提供一个sample吗

**Comment by qwertccc** [comment]
这是那个ps安装包链接: https://pan.baidu.com/s/1ehyi1yzriGtIq34Mr12jaw 密码: uxxd

我这里不是所有文件都这样儿，yyets下美剧，有的就不行，有的就没事儿，反正mp4封装的视频文件，文件头没坏也凑合看，所以当时也没注意

**Comment by Kyle-Kyle** [comment]
已确认。
目前可获得两个md5。一个是和文件绑定在一起的（插件正在使用的）。另一个是下载时服务器动态获得的。
问题就在下载时服务器算出来的md5和文件绑定的md5不同。疑似是文件在baidu服务器上已经被有所修改。和原本的md5不同（植入？）。
这个是否要修改有待商榷。

**Comment by Kyle-Kyle** [comment]
如果这种情况多的话可能就要考虑使用服务器算出来的md5进行校验了

**Comment by qwertccc** [comment]
等下，我马上找个独一无二的以前没有传过任何地方的文件，我传上去，再下回来，如果报错，就看看本地原始和下载后文件的hash

**Comment by Kyle-Kyle** [comment]
[#2863c4 100MiB/100MiB(100%) CN:0] [Checksum:#2863c4 53MiB/100MiB(53%)]        
05/19 10:43:02 [ERROR] Checksum error detected. file=/Users/Kyle/Downloads/哥谭.Gotham.S04E22.End.中英字幕.HDTVrip.720P-人人影视 (1)-001.mkv

Interesting.

**Comment by Kyle-Kyle** [comment]
没出高速链接的问题我可能也要看一下。可能和视频是新上传的有关。这个问题另开一个issue吧

**Comment by Kyle-Kyle** [comment]
没出高速链接的问题我看了。刚上传的文件是不能下载的。所以在检测链接有效性的时候所有hlink都被过滤掉了。不用修。

**Comment by qwertccc** [comment]
我估计是新上传的文件还没有同步到他们服务器吧，估计也过阵子
