### ISSUE TITLE
the speed is 10

### ISSUE THREAD

**Issue by Jeff-Kook** [Kyle-Kyle/baidudl#104]
服务器把我的ID拉入黑名单了吗？
连续下载好多个文件后，下载速度
the speed is 10
原来是 the speed is 80
换一个账号倒是能回到80.但是想问一下，是不是我那个账号以后的下载速度都只是10了？

**Comment by Kyle-Kyle** [comment]
最新版本应该全是80...另外.这个被封的账号大概在一个星期或者两个星期后会被解封

**Comment by Kyle-Kyle** [comment]
另外.这个插件在不登陆状态下也是可以用的

**Comment by Jeff-Kook** [comment]
使用新版本后，问题解决了。无需登录，the speed is 80，虽然实际网速没能如愿，但看来也只能这样了
