### ISSUE TITLE
不支持https协议吗

### ISSUE THREAD

**Issue by RecluseWind** [Kyle-Kyle/baidudl#105]
我的Aria2部署了ssl证书，只能通过https远程下载。但是使用baidudl时，GLinks和HLinks都没有链接啊。点击RPCDownload提示“Warning: HLinks should be generated before download!”

**Comment by Kyle-Kyle** [comment]
支持的。在options里可以设置。
使用aria2下载的流程。
1. 在options页面把RPC Mode设置成on.
2. 添加你的rpc服务器
3. 进入页面生成hlinks。
        - 如果是在分享页面就在点开插件图标后等5秒。直到链接出现。
        - 如果是在个人主页。就选中你要下载的文件然后点generate。等5秒直到链接出现。
