### ISSUE TITLE
Broken connections when doing parallel downloading

### ISSUE THREAD

**Issue by wyt666** [Kyle-Kyle/baidudl#106]
![ba9fa9ce-9074-40bf-b511-ecaea7c62731](https://user-images.githubusercontent.com/15173846/41275129-7829662a-6e52-11e8-9c70-bd891ead7d0c.png)
![fca7f0ed-7605-4294-8f72-4d5015b4d1c7](https://user-images.githubusercontent.com/15173846/41275120-71d3e584-6e52-11e8-8ba7-7bd8ef6f6ead.png)

**Comment by Kyle-Kyle** [comment]
根据你的截图。你应该是同时下载了好多文件。我稍后看一下。

**Comment by wyt666** [comment]
好的，是的，同时下载了多个文件

**Comment by qwertccc** [comment]
max-connection-per-server

官方版最大16，找个第三方编译突破这个限制的，设置大一些就快了

**Comment by Kyle-Kyle** [comment]
@qwertccc 不是这个问题。应该是多个文件一起下载，溢出的线程速度太慢被当做无效线程被关掉了。当有其他文件被下载完，溢出不存在了，线程被关掉的后果就出现了。
@wyt666 解决方法是在一个个文件下载。在aria2c的选项中加入-j 1。

**Comment by qwertccc** [comment]
噢噢噢，这意思

我在web版aria2的控制台看见单个任务就16线程

**Comment by Kyle-Kyle** [comment]
@qwertccc .....我正在考虑修改默认模式。。现在默认是快速模式。只会获得一条链接。所以是16线程。但是如果开启rpc模式（新选项），就会获得更多链接，平均10几条吧，160线程不在话下。

**Comment by qwertccc** [comment]
默认打开呗，快很多啊

现在大家电脑跟路由应该配置都不低吧，我觉得没啥问题哈哈

**Comment by qwertccc** [comment]
一共我看30来个服务器，单服务器16线程拢共也才600多，弄个第三方编译的aria2，改单服务器32一共单任务也就1200多，我琢磨1200多的话一般现在硬件都没啥问题啊
