### ISSUE TITLE
Download speed is slower by time has passed, Authorization failed

### ISSUE THREAD

**Issue by kurodabin** [Kyle-Kyle/baidudl#107]
When I started download, the speed is around 800kb/s (my max speed is around 7mb/s), then it's slower and slower.

About 30 mins later, I have an error and the download is stopped.
![image](https://user-images.githubusercontent.com/22904468/41516641-2250e36c-72e0-11e8-8ba5-4efaade94e10.png)

I've tried to download again multiple times but this error still happen.

What should I do? Thank you very much!

Some infos:
- Signed in pan.baidu.com before starting download.
- Downloading only 1 file at the same time.
- Using google chrome with the latest update.
- Using windows 10 home with the latest update.

**Comment by Kyle-Kyle** [comment]
https://github.com/Kyle-Kyle/baidudl/blob/master/README.md
follow Method 2.

**Comment by Kyle-Kyle** [comment]
This method should allow you to reach the max download speed.

**Comment by raikiry1991** [comment]
what is RCP   can you tell me 
i can't download from pan.baidu 
it is very slow

**Comment by kurodabin** [comment]
First of all, thank you very much for your quick reply and support me!
I've tried your method 2 as well. But the problem still happened.

When I use method, the speed at downloaded 1% is around 2mb/s (it's look better than before)
But it's slower and slower... I feel like ETA always in 30mins. (File size: 4.2GB)

Then the speed when downloaded 90% is around 500kb/s.
The seed when downloaded 93% is round 50kb/s.

After that, the download is stopped with the same error I've mentioned above.

Following are my captures.

At 1%
![image](https://user-images.githubusercontent.com/22904468/41809023-f3ff744e-7710-11e8-9fb1-d6849d71b965.png)

At 90%
![image](https://user-images.githubusercontent.com/22904468/41809026-0683e71c-7711-11e8-8b1c-a3a26dcdd66d.png)

At 93% and stopped with error.
![image](https://user-images.githubusercontent.com/22904468/41809030-17e44f92-7711-11e8-881a-a986fb004367.png)

Thank you again!

**Comment by Kyle-Kyle** [comment]
It looks like a new mitigation from baidu.
For now, what you can is is just stop the task and restart again. Then it will start from where it stops.

**Comment by kurodabin** [comment]
Oh, I see. Thank you for your support!!
I'm sorry but I don't get the "restart" thing, is that mean I need to use the same HLink to download in RPCDownload?

**Comment by Kyle-Kyle** [comment]
@kurodabin not necessary the same HLink, you just need to RPCdownload the same file again.

**Comment by Kyle-Kyle** [comment]
@kurodabin I'm working on the counter measure.

**Comment by kurodabin** [comment]
Okay thank you very much!!

**Comment by Kyle-Kyle** [comment]
A temporary fix has been committed, the problem should be eliminated for now (hopefully). The final fix will require a new module to drive aria2 which I have got no time to do for now.
