### ISSUE TITLE
使用教程不是很懂？

### ISSUE THREAD

**Issue by moximoxi233** [Kyle-Kyle/baidudl#108]
baidudl/baidudl_rpc/Windows/aria2c.exe是直接下这个吗？？？？

**Comment by moximoxi233** [comment]
![image](https://user-images.githubusercontent.com/40336671/41536555-8490c6fc-7338-11e8-8ce8-d0dd35b6b38b.png)

**Comment by Kyle-Kyle** [comment]
......
https://github.com/Kyle-Kyle/baidudl/files/2066712/extension.crx.zip
先下载这个文件。extension.crx直接拖到chrome里。
双击打开刚才你下载的baidudl_rpc.exe
