### ISSUE TITLE
下载连接处显示NA，没有下载链接

### ISSUE THREAD

**Issue by hopefully2333** [Kyle-Kyle/baidudl#109]

**Comment by Kyle-Kyle** [comment]
因为是文件夹。进文件夹再使用。

**Comment by hopefully2333** [comment]
进入文件夹之后还是加载不出链接

**Comment by Kyle-Kyle** [comment]
方便的话请给出链接。不太应该出现这种情况。按理来说NA只会针对文件夹出现。

**Comment by hopefully2333** [comment]
FileName | GLinks | CopyAll | HLinks | CopyAll | Refresh | Generate

 GLinks 和 HLinks 下面的部分是空的，然后左下角一直显示 lording...

**Comment by Kyle-Kyle** [comment]
根据你的描述，大概率是网络连接问题。我自己有遇见过。这个时候换个wifi就好了。

**Comment by Kyle-Kyle** [comment]
也可以试着等一等。刷新分享页面要多久，插件的加载就要多久。

**Comment by qqldd** [comment]
我也遇到了下载GLinks 和 HLinks 下面全是空的

**Comment by Kyle-Kyle** [comment]
@qqldd 你应该是在个人主页下，空的是正常的。个人主页要手动generate

**Comment by hopefully2333** [comment]
谢谢啦！等周末的时候我再试试。(*^_^*)

**Comment by qqldd** [comment]
@Kyle-Kyle 仔细看了下README，好像确实是分享的时候用这个插件才有链接，等我试下，谢谢！

**Comment by fhench57g** [comment]
My chinese is patchy but from what I understand the issue that OP has is kind of similar to mine, in that I can't see any links and I do not have the "generate" button. It is just stuck at "Loading..." for me. [Here is a screenshot of my issue](https://imgur.com/dPtYR0H).     

From what I gather there are a few possible explanations/solutions for the issue:
1) "根据你的描述，大概率是网络连接问题。我自己有遇见过。这个时候换个wifi就好了。" --> there is some connection issue. My wifi is fine though so does this mean there is an inherent issue with the file I am trying to download?

2) "也可以试着等一等。刷新分享页面要多久，插件的加载就要多久。" 
3) "@qqldd 你应该是在个人主页下，空的是正常的。个人主页要手动generate"
4) "@Kyle-Kyle 仔细看了下README，好像确实是分享的时候用这个插件才有链接，等我试下，谢谢！" 

--> Unfortunately I don't understand 2) to 4), could you kindly explain what they mean?

**Comment by Kyle-Kyle** [comment]
@fhench57g Thank you very much for liking this extension and your patience to read Chinese, LOL!

1. There may be some networking issue(which should be fine in your case?)
2. You can try to click the `refresh` button and wait for a few seconds. The time to load for extension is the same as the time it takes to reload the page.
3. (May not be related to your issue) If you are at your home page, it's expected to see blank in GLink and HLink. Because you need to manually generate links at your home page.
4. He find that the extension can auto grab links in share page(some thing like https://pan.baidu.com/s/*).

**Comment by fhench57g** [comment]
@Kyle-Kyle Thank you for your reply!

Can I clarify whether I need to be logged into an account for this extension to work? I could generate links in the past without being logged in, but in 3. you talk about manually generating links at your home page which I presume can only be done if logged into an account?

As for 2., whenever I click `refresh` the extension will be stuck at "refreshing" and no links will be generated, and if I refresh the whole page and try again the same thing happens again

**Comment by Kyle-Kyle** [comment]
@fhench57g 
1. You don't have to be logged in to use this extension. You can use it in share page.
2. There are several reports on this issue, but I have not encountered it by myself. To solve this, could you provide debugging information? It is in background page. You can see it by open chrome://extensions and click `Inspect views background page`

**Comment by qqldd** [comment]
Update: The extension works for pan.baidu.com/s/... i.e. the shared links.

Thanks!

@fhench57g If someone share you the link like pan.baidu.com/s/..., I believe you don't need to log in into baidu.com

If you have an account on pan.baidu.com. You need to share it to yourself and get the pan.baidu.com/s/... link. After that, this extension works!
