### ISSUE TITLE
一个小问题，希望能解释一下

### ISSUE THREAD

**Issue by silence** [Kyle-Kyle/baidudl#11]
![20170712153526](https://user-images.githubusercontent.com/25074202/28106888-2e6c8b3a-6718-11e7-8ea5-cc78ad8db482.png)
家里是20M光纤 使用了迅雷快鸟进行提速，左图是拓展导出链接的下载速度，右图是油猴批量打包下载的速度。我起初以为是cookies的原因，但退出登录后速度仍然为左图，下载其它的链接(非百度网盘链接)都是10Mb/s。应该是生成的链接问题，不懂求解

**Comment by Kyle-Kyle** [comment]
这两个没有可比性。左图是单个文件。右图是打包下载。两个方式获取的链接是属于不同服务器的，所以速度不一样。另外。我目前只知道IDM支持打包下载
