### ISSUE TITLE
What is GLinks and what is HLinks?

### ISSUE THREAD

**Issue by ahmedtds** [Kyle-Kyle/baidudl#110]
What's the difference between those links? Whey are there 2 links. I think you could be a little more clear on that?
What is GLinks and what is HLinks?
Which one should I use?

Thanks

**Comment by Kyle-Kyle** [comment]
You should use HLlinks.

GLink is like a gate link, you visit it and you will be redirected to other CDN servers.
HLlinks are links with high download speed. They are collected from listing CDN servers and filtered before you get them. Generally speaking, a HLink is faster than GLink. What's more, you can get multiple different HLinks at the same time. If you pass them to aria2, you will get a huge download speed boost.

**Comment by ahmedtds** [comment]
I see, thanks for info. I also have one more question/suggestion. Is it possible to make aria2 use more than 16 connections when you send it via RPC? It was downloading with 16 but I think speed would be much better if that could be increased?

**Comment by Kyle-Kyle** [comment]
of course! that's the main point of this extension!
You should follow method 2 in README.md. In this way, the max connection number can be enlarged to 100(this number can be configured in options page)

**Comment by CarolSum** [comment]
how can i generate HLinks? I can't find a 'generate' button
