### ISSUE TITLE
Frequently encountered problems

### ISSUE THREAD

**Issue by bearbunny** [Kyle-Kyle/baidudl#112]
it's not working any more

**Comment by Kyle-Kyle** [comment]
how?

**Comment by bizkitj** [comment]
![image](https://user-images.githubusercontent.com/25093538/41828435-c5b69e3e-7867-11e8-8b39-c04fce3f2684.png)

It's all empty. Am I doing something stupid?

**Comment by bearbunny** [comment]
@Kyle-Kyle 
![s26](https://user-images.githubusercontent.com/39623361/41828708-f4f8f770-7860-11e8-9e63-30e522f61d8f.jpg)

I can't click on button anymore. Before that It's work good for other files except .rar or .zip. I often have CRC checksum error and can't extract file (file size 1GB++)

**Comment by Kyle-Kyle** [comment]
@bizkitj In home page, you need to generate your links first. 
For those two `NA` ones, they are folders which are temporally not supported.
For files, you need tick what you want to download an then click `generate` to generate links first.
@bearbunny Good question, that's may be some problems with your weblink. Make sure your url starts with `https://pan.baidu.com`(yours maybe `https://yun.baidu.com` which is deprecated and not included in this extension.). What you need to do is simply change the `yun` to `pan`.

**Comment by Kyle-Kyle** [comment]
@bearbunny In terms of your questions about .rar and .zip, I think they have been fixed several commits ago.

**Comment by Kyle-Kyle** [comment]
@bearbunny I will try to fix the `yun.baidu.com` problem. Since the small sample size, it will take some time to do verification. I don't want to left anything broken in this project.

**Comment by Kyle-Kyle** [comment]
@bizkitj Looks like your problem is not unique, I will include it in README.md later.

**Comment by KoolPal** [comment]
Hi @Kyle-Kyle,

Thanks for this awesome piece of code!

I am chiming in to say that there seems to be some issue lately!

My url shows  `pan.baidu.com` yet the download url is not generated. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/454883/42071280-24ec8e46-7b78-11e8-8e3a-857415b1103c.png)

Please let me know if I can help in any way.

Thanks again!

**Comment by Kyle-Kyle** [comment]
@KoolPal Weird. But I did encounter some weird stuff which is not the extension's fault. There are some ghosts in baidu side(shrug).

**Comment by KoolPal** [comment]
@Kyle-Kyle No worries. Understandable! Thanks again for the good work!
