### ISSUE TITLE
不好意思，使用的时候出现了一些问题.....

### ISSUE THREAD

**Issue by E100WT** [Kyle-Kyle/baidudl#113]
(三个)文件提取Hlink的时候可以成功得到(三个)链接,但在IDM里使用时出现了问题:
1,文件.以往使用油猴插件+IDM的时候都是自动的zip格式，但在使用您的插件时出现了名称+大小+格式在IDM选择下载时都显示"未知"的情况;
2,结果:"服务器响应显示您没有权限下载此文件";"备注":HTTP/1.1 403Forbidden";最终导致无法开始下载；
由于不知道如何解决问题，向您求助...本人学生狗一枚，可能无法及时回答，还请谅解，谢谢您了.

**Comment by Kyle-Kyle** [comment]
每一条链接在获取的时候都会在浏览器中被试验过（不会真的下载），说明这条链接在获取链接的浏览器里是可以用的。你可以试一下把链接粘贴到获得链接的浏览器里试一下能不能下载。
如果能的话，你需要改一下idm的user-agent，改成和浏览器里的一致。
（我猜测你应该是有多个浏览器，idm绑定的和插件绑定的不是同一个，所以导致了这个问题。）

**Comment by E100WT** [comment]
因为确实是不能马上验证,所以只有等到下周末再来试试了.
请问idm的绑定是什么意思,我在chrome浏览器上是有idm的扩展插件的啊(虽然不知道是干嘛用的...

**Comment by Kyle-Kyle** [comment]
@E100WT 就是IDM在发送请求的时候是模拟的什么浏览器。我的猜想是你的IDM模拟的不是chrome，所以有这样的问题。

**Comment by E100WT** [comment]
您好，好久没有回复您了。请问user-agent在哪里设置？
而且好像若是下载站点被墙了之后idm若没有相应设置是无法开始下载的(比如windows的网盘)，请问该如何设置呢

**Comment by Kyle-Kyle** [comment]
我不常用idm的。你可能要自己去搜一下。

**Comment by E100WT** [comment]
我的确是有三个浏览器。。但我就是找不到那个设置，有相应的中文名吗

**Comment by Kyle-Kyle** [comment]
其实。你可以用这个项目的专用下载器的。配合这个插件的话，专用下载器的速度是快过idm的。链接：https://github.com/Kyle-Kyle/baidudl/files/2066709/baidudl_rpc_Win.zip

**Comment by E100WT** [comment]
？？请问如何使用，只有两个文件啊

**Comment by E100WT** [comment]
您好。尝试了一下，速度还是没有IDM下载得快。
没有更改您所说的user-agent现在也可以开始下载了，不知道是什么情况。（难道是因为现在我正开着百度的超级会员？？）

**Comment by Kyle-Kyle** [comment]
https://github.com/Kyle-Kyle/baidudl/blob/master/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.md
参考方法二使用。
