### ISSUE TITLE
似乎无法刷出下载地址

### ISSUE THREAD

**Issue by lei12345** [Kyle-Kyle/baidudl#114]
@Kyle-Kyle 
2.0.1
一直无法刷出下载地址，GLinks/HLinks都是空白的，refresh后一样，Generate后，复选框的勾全被清除。
网络是有线的。系统是win10 x64 + chrome x64。是不兼容64位吗？

开始点击时：有loading...字样，refresh时很快闪过refreshing...

1.4/1.3
点击Generate后，会把打开的百度盘目录重置到根目录。且无下载地址。

补充：1.3.5 大概在半年前是正常的，近段时间没用。

**Comment by lei12345** [comment]
补充：1.3.5 大概在半年前是正常的，近段时间没用。

**Comment by Kyle-Kyle** [comment]
是在个人主页下吧？然后勾选了文件点generate。什么都没有出现？我有空看一下。
我的测试都是在64位的环境下做的。

**Comment by Kyle-Kyle** [comment]
用法有一点点改变。点完generate要等3秒钟左右。你先试试等一等能不能出链接。
关于重置到根目录的。可能是有Bug。

**Comment by jiangqinhua** [comment]
最近这几天有的可以 有的不行

**Comment by jiangqinhua** [comment]
![image](https://user-images.githubusercontent.com/36619735/43367588-028458bc-9382-11e8-80eb-9ef72dcca53d.png)
没显示NA 就什么都没有

**Comment by Kyle-Kyle** [comment]
@jiangqinhua 
个人主页下链接要手动勾选然后点`Generate`

**Comment by jiangqinhua** [comment]
感谢,请问 用rpc功能是不是需要电脑安装aria2先,
还有我也想帮忙 请问需要哪方便的知识呢, 
现在是cs在校生.

**Comment by GeofferyGeng** [comment]
新版本需要在分享链接才可以prcdownload

**Comment by jiangqinhua** [comment]
不需要。就像作者说的一样 就可以下载了速度客观

**Comment by Kyle-Kyle** [comment]
@jiangqinhua 远端下载很容易。在服务器上运行aria2。然后在电脑上将rpc server的ip设置成你自己服务器的ip即可。

**Comment by jiangqinhua** [comment]
@Kyle-Kyle 谢谢
