### ISSUE TITLE
请教：下载速度的含义？

### ISSUE THREAD

**Issue by bossox** [Kyle-Kyle/baidudl#115]
开始下载时，显示

> the speed is 80

查看源代码这个数值来自 `hlink.searchParams.get('csl')`。
小白想请教一下这个数字是怎么算来的？具体含义是？
我知道它确实意味着速度的快慢。

**Comment by Kyle-Kyle** [comment]
个人的理解是connection speed limit。就是单线程的下载速度上限（实测过）。
你可以试试把获得的一条链接放到浏览器里下载，速度不会超过这个上限。
