### ISSUE TITLE
Cannot generate hlinks

### ISSUE THREAD

**Issue by daihakken** [Kyle-Kyle/baidudl#116]
Hlink appears as blank even though it seemed to be fetched correctly in the bg page.
![2018-07-29 23_01_18-](https://user-images.githubusercontent.com/13048125/43367669-49f64f12-9340-11e8-89d1-294a3ebc4ba6.png)
![2018-07-29 23_01_54-devtools - chrome-extension___lflnkcmjnhfedgibjackiibmcdnnoadb__generated_backgr](https://user-images.githubusercontent.com/13048125/43367675-5f4f749c-9340-11e8-8eaf-1ef2b6204550.png)

This happens with the file which is not downloaded frequently.

**Comment by Kyle-Kyle** [comment]
The extension works well according to the log.
There is a very rare case which I have encountered several times during personal testing. That is all hlinks can not pass filtering phase.
I recommend you click the `Refresh` button to exclude this possibility.

**Comment by daihakken** [comment]
Those captures were after multiple refreshes (say, about 10 times). In network tab of the inspector, every baidupcs link connected successfully, but nothing shows in the pop up. Hence, I created the issue for you to investigate.

On 30 Jul 2018, at 02:39, Kyle Zeng <notifications@github.com<mailto:notifications@github.com>> wrote:


The extension works well according to the log.
There is a very rare case which I have encountered several times during personal testing. That is all hlinks can not pass filtering phase.
I recommend you click the Refresh button to exclude this possibility.

**Comment by Kyle-Kyle** [comment]
Interesting.
So here is a problem: "every baidupcs link connected successfully". If the extension works as expected, at least some links should return "canceled" or "failed".
Could you provide the content of `Network` tab of the background page?

**Comment by Kyle-Kyle** [comment]
BTW, I mean the `Refresh` button in the extension, not refreshing the page, if you misunderstood.

**Comment by Kyle-Kyle** [comment]
I fixed a bug which causes similar problem just now. Could you clone it and try again?

**Comment by psc2350** [comment]
The latest clone seems to works.
Chrome store version needs an update.

**Comment by psc2350** [comment]
It seems link HLink can not be generated for some files again.
链接: https://pan.baidu.com/s/1MKCpHREHQqolS7VcM_3muA 密码: nkhb

**Comment by Kyle-Kyle** [comment]
@mjuzikfrik it works for me after 10s.
@psc2350 @mjuzikfrik Are you using the latest github version?

**Comment by psc2350** [comment]
@Kyle-Kyle I have just updated 2.0.4. HLink was finally able to be generated. However, I am getting really slow connection in rpcdownload. Only a few KBs.

**Comment by Kyle-Kyle** [comment]
@p

**Comment by Kyle-Kyle** [comment]
@mjuzikfrik I will look into it.

**Comment by Kyle-Kyle** [comment]
#125

**Comment by Kyle-Kyle** [comment]
It is related to baidu's previous mitigation measure. But the mitigation measure has been discarded now, so it is safe to close this issue.
