### ISSUE TITLE
有的文件无法刷出hlinks

### ISSUE THREAD

**Issue by GeofferyGeng** [Kyle-Kyle/baidudl#117]
最近在百度云找到的电视剧资源有时会出现刷不出hlinks的情况，完全没有规律，可能31集还可以用，但是
32集就失败了

**Comment by Kyle-Kyle** [comment]
第二例报告。然而我自己没有遇到过。是否能够提供一些具体信息。

**Comment by GeofferyGeng** [comment]
附一张图，刚刚碰到的情况。: (    PS:如果是个例的话是否与网络配置有关呢（因为不太懂插件的原理，只是猜测）
[图片链接（百度云）](https://pan.baidu.com/s/1fGRU6lrmcMGwP0GrPqz_0Q)

**Comment by Kyle-Kyle** [comment]
嗯。这个情况就很有意思了。我看一下。

**Comment by Kyle-Kyle** [comment]
已复现。

**Comment by Kyle-Kyle** [comment]
插件的问题。在一个目录下文件特别多的时候可能会出现。最新版本已修复。

**Comment by Kyle-Kyle** [comment]
bug的原因是在做filtering的时候，大量的网络流量让百度认为这是恶意流量而不返回正常的link。

**Comment by Kyle-Kyle** [comment]
嗯。重新看了一眼。你发的截图里文件不算多，需要你确认一下。

**Comment by GeofferyGeng** [comment]
我应该使用的是2.0.2，我把图中文件的云链接附上，链接: https://pan.baidu.com/s/1nOXv_vNWAoocuk5-2xT4lg 密码: idxj  （此刻）我又去试了一下，发现仍然无法获取中间的两个文件，事实上即使把他单独拿出来仍然是无法获取hlinks，好像特定的文件就是无法获取链接，会不会某度云内部会把一些文件划为黑文件，不让人下载

**Comment by Kyle-Kyle** [comment]
试了一下。文件本身都无法下载。根据以往经验，过一会儿应该就可以。或者是保存到自己的网盘里也可以。这应该是百度本身的问题。

**Comment by GeofferyGeng** [comment]
了解了~

**Comment by Kyle-Kyle** [comment]
重新看了一下你发的文件，确实有Bug，2.0.3已修复。
