### ISSUE TITLE
LAN設置

### ISSUE THREAD

**Issue by psc2350** [Kyle-Kyle/baidudl#118]
想問下
同一個路由器下
如何設置可在一台機器上打開baidudl
另一台選RPC Download的時候
開著baidudl的機子可以下載

**Comment by Kyle-Kyle** [comment]
打开baidu-dl的options页面。加入rpc server的信息即可。

**Comment by Kyle-Kyle** [comment]
rpc server也就是有打开了baidu-dl_rpc的那台电脑的ip地址
