### ISSUE TITLE
点击generate没有反应,请问一下这个插件现在是还能正常运行的吗?

### ISSUE THREAD

**Issue by fangguangyang** [Kyle-Kyle/baidudl#119]
![image](https://user-images.githubusercontent.com/14014903/43987163-379f56ec-9d4f-11e8-9775-05c7472f9fc4.png)

**Comment by Kyle-Kyle** [comment]
左边先选中需要的文件

**Comment by fangguangyang** [comment]
勾选了的,点击generate,被勾选的会失去勾选状态,然后就没有后续反应了

**Comment by fangguangyang** [comment]
![gif](https://user-images.githubusercontent.com/14014903/43988957-85a11e2e-9d73-11e8-820c-86d2092b4089.gif)

**Comment by Kyle-Kyle** [comment]
已修复。请测试。

**Comment by rocdeng** [comment]
刚试了还是不行哦，需要重装吗？

**Comment by fangguangyang** [comment]
![gif](https://user-images.githubusercontent.com/14014903/43989211-f82263be-9d77-11e8-8deb-848a93710d40.gif)

**Comment by fangguangyang** [comment]
看起来还是不行哦...

**Comment by rocdeng** [comment]
刚才也试了clone了最新版本装了unpack的版本，还是不行。
发现有一个错误，不知道和这个是不是有关系？
<img width="622" alt="wx20180811-164131 2x" src="https://user-images.githubusercontent.com/413922/43989918-d0ed4e54-9d85-11e8-94b4-9903c05ac2ef.png">

**Comment by rocdeng** [comment]
重启了一下Chrome，再试功能正常了，也没有报这个错误了

**Comment by GeofferyGeng** [comment]
你用的版本太老了，现在已经没有generate按钮了，好像自动会，附百度云链接   链接: https://pan.baidu.com/s/1_zBEP48l3cT5B0vb1x5cjQ 密码: bkue

**Comment by Kyle-Kyle** [comment]
@GeofferyGeng 
有的。在个人主页下和在分享页面下插件的表现是不一样的。

**Comment by fangguangyang** [comment]
我是下载最新的代码用谷歌打包插件的,不是商城下载的,刚才点了上面的分享链接,是可以生成一个hlink的下载链接,我自己网盘的东西还是不行

**Comment by Kyle-Kyle** [comment]
@fangguangyang 修复了另一个可能有关的问题。

**Comment by GeofferyGeng** [comment]
，，，我竟然之前没用过！欸，我记得之前2.0.0的时候好像还没有的，然后一直使用分享链接，-.-

**Comment by GeofferyGeng** [comment]
我写了一个启动器（之前一直用你的bat启动，但是还得打开一个网页查看进度速度，强迫症表示要受不了了），如果有兴趣的话可以看下 @Kyle-Kyle

**Comment by Kyle-Kyle** [comment]
@GeofferyGeng 稍微看了一下。感觉很好。
我觉得你给了我一个提示。为什么要自己写启动器呢。直接用别的项目就可以了，更加user friendly。
windows/mac的话我会考虑用别的项目来替代现有的启动器。linux的话提供一个shell script应该就可以了。
windows下暂定使用你的项目。我会再做一些调查。
感谢支持。

**Comment by fangguangyang** [comment]
@Kyle-Kyle 刚试了,运行正常

**Comment by protocold** [comment]
不知道什麼原因我用離線下載了這連的檔案後不能用baidu-dl下載, 点击generate,被勾选的会失去勾选状态,然后就没有后续反应了.. 已經試了重启及git clone最新的版本. 

 magnet:?xt=urn:btih:e156ce70fee6464549fef653c8468aecb3e7e9f1&dn=Black.Panther.2018.1080p.BRRip.x264-BRRIP&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969
