### ISSUE TITLE
获取链接后在IDM无法下载

### ISSUE THREAD

**Issue by Doraemon9** [Kyle-Kyle/baidudl#12]
![image](https://user-images.githubusercontent.com/30166502/28196645-79ee4b58-6884-11e7-92b4-b671eccd64eb.png)
 试了好几个文件都是这样 
谢谢解答

**Comment by Kyle-Kyle** [comment]
感觉像是网络的问题。可以换个浏览器试试或者直接用浏览器下载试试。如果可以下载说明是idm的设置或者版本有问题
