### ISSUE TITLE
setting

### ISSUE THREAD

**Issue by apt42541** [Kyle-Kyle/baidudl#120]
how can i setting to download max speed now i download 800kb

**Comment by apt42541** [comment]
![image](https://user-images.githubusercontent.com/12625408/44094852-775e4b80-a001-11e8-8078-1a7e0a3839a2.png)

**Comment by apt42541** [comment]
"[Feather@TSDM][intervencion@NYAA][うえきの法則][DVDRip][TV01~51Fin][480P][MKV].part04.rar" is added to http://127.0.0.1:45233/jsonrpc. The speed is 78

**Comment by Kyle-Kyle** [comment]
You can't. The solution to your problem is generate a link again. Each time you generate a link, the download speed with the link can be different.

**Comment by apt42541** [comment]
there another way?
