### ISSUE TITLE
speed is null

### ISSUE THREAD

**Issue by kgg-hs** [Kyle-Kyle/baidudl#124]
Why always spees is null? i cant download anything, i have speed about 5-15 kb/s in last days. Whats the problem?? (It used to be better)

**Comment by cnjn** [comment]
我也是这个问题，昨儿开始，我还以为被封号了，但退出登录依旧没有速度
![image](https://user-images.githubusercontent.com/30923815/44617537-ad3fcb00-a896-11e8-9206-350c93baedf9.png)

**Comment by Kyle-Kyle** [comment]
null is expected.
I will look into the slow download speed problem

**Comment by Kyle-Kyle** [comment]
#125

**Comment by Kyle-Kyle** [comment]
fixed
