### ISSUE TITLE
Baidu's new mitigation method and its bypass

### ISSUE THREAD

**Issue by Kyle-Kyle** [Kyle-Kyle/baidudl#125]
Bypass:
You have to get the newest  clone and log into your account.

Notice:
This may result in your account banned.

I'm not capable enough to make anonymous downloads continue for now.
Sorry about that.

**Comment by kgg-hs** [comment]
Ok now we havent "null speed" but downloading isn't start. We are testing this now in three people in voice. downloading doesn't move for 35 minutes
![screenshot_2](https://user-images.githubusercontent.com/42694138/44620442-f5fa8280-a89c-11e8-8c74-19d1cef3713b.png)

**Comment by kgg-hs** [comment]
![i4vttzklusw](https://user-images.githubusercontent.com/42694138/44620478-a5cff000-a89d-11e8-9502-cd9392c77c54.jpg)
screen of my interlocutor

**Comment by arielcasari** [comment]
still with error even logged

**Comment by Kyle-Kyle** [comment]
Could you provide any sample?
I myself haven't encountered this problem.

**Comment by GreatApo** [comment]
I also have similar problems. What will you need that will help you?

![image](https://user-images.githubusercontent.com/9620510/44797536-19347300-abb8-11e8-95bb-71685fbc9997.png)

**Comment by Kyle-Kyle** [comment]
@GreatApo 
I think I need a sample. I myself cannot replicate the problem you mentioned.

**Comment by liam-maps** [comment]
Hi! @Kyle-Kyle 
This link may help.
It generates the same error
https://pan.baidu.com/s/1c0y6MSK

**Comment by Kyle-Kyle** [comment]
Should have been fixed now.

**Comment by Kyle-Kyle** [comment]
Now you can continue downloading anonymously.
