### ISSUE TITLE
点击 图标后  等待2分钟并没有生成链接

### ISSUE THREAD

**Issue by babyhai** [Kyle-Kyle/baidudl#127]
![g u4 p jle9v150bqantm65](https://user-images.githubusercontent.com/22759331/45133389-81421500-b1c7-11e8-8469-c61d9de61991.png)

GLinks   HLinks  貌似生成不了，求解？？

**Comment by AnestLarry** [comment]
选中后点生成(Generate)?
<hr>
新用法似乎是加密分享后在分享页面打开baidudl吧(如果资源没问题的话

**Comment by Kyle-Kyle** [comment]
shi

**Comment by wuwentao** [comment]
我第一个文件成功了，第二个文件后refres了一下，一直loading没反应，点击generate依然没有结果，用的是git最新的版本，chrome手工加载文件夹。

**Comment by Kyle-Kyle** [comment]
@wuwentao 你可以一次性全选。然后generate。看看第二个文件能不能出来。

**Comment by Kyle-Kyle** [comment]
@wuwentao 大概知道是什么原因了。正常生成的时间是10秒内，但如果文件的资源特别不好，可能要等很久才能出hlink，我遇到过1~2分钟的。

**Comment by cnjn** [comment]
多线程不给力啊，我一次生成100个链接时总有几个出不来，我直接拆分成了10份，每次生成10个就好多了。

**Comment by Kyle-Kyle** [comment]
@cnjn 你说的问题确实存在。有时候是因为网络请求太频繁，被baidu拦住了。也有时候只是因为生成的太慢。
