### ISSUE TITLE
Is there any way to batch download?

### ISSUE THREAD

**Issue by liam-maps** [Kyle-Kyle/baidudl#128]
I want to download more than 100 links, and processing one by one is time consuming.
Is there any way to load several links into the extension?
Thank you for your work.

**Comment by liam-maps** [comment]
Maybe add an option like "Download All by RPCDownload?

**Comment by Kyle-Kyle** [comment]
Emmm. That sounds a good idea.

**Comment by Kyle-Kyle** [comment]
It is online now.
