### ISSUE TITLE
2018.10.1好像失败了

### ISSUE THREAD

**Issue by liveroute** [Kyle-Kyle/baidudl#130]
HLINK GLINK读不出来了。

**Comment by Kyle-Kyle** [comment]
我这还可以..文件问题？

**Comment by liveroute** [comment]
Chrome 版本 69.0.3497.100 x64
baidu-dl 2.0.3
前天还可以，下载了5个文件测试，昨天就读不出链接了。
禁用了除baidu-dl外的其它扩展任然读不出

**Comment by conphi** [comment]
我也是同样的情况，下载了一个大文件，过了6个小时后再下载时候，发现无法调出Glinks 或者HlinKs了

**Comment by Kyle-Kyle** [comment]
很有意思。最近有好多起这样的报告。然而我一个都不能复现。这就很尴尬了。

**Comment by conphi** [comment]
解决办法：分享一下，打开分享页，再下载就可以了，没问题，效果杠杆好！

**Comment by liveroute** [comment]
> 解决办法：分享一下，打开分享页，再下载就可以了，没问题，效果杠杠好！

确认可行。谢谢
