### ISSUE TITLE
可以同时运行两个baidudl_rpc.bat？

### ISSUE THREAD

**Issue by mikezang** [Kyle-Kyle/baidudl#132]
如果同时运行两个baidudl_rpc.bat是否可以提高下载速度？

**Comment by Kyle-Kyle** [comment]
先说结果：不能。
如果你说的是单个文件：只能通过一个aria2 server(baidudl_rpc)来下载，多开无效。
如果你说的是多个文件：完全可以通过一个aria2 server来下载（同时下载多个文件），在这种模式下，下载上限取决于baidu方面的防御措施和你家的带宽。最近baidu的限制比较松，我刚才试了一下应该能到5M/s(比较大的可能是我宿舍的带宽上限)。理论上限可能是10M~30M/s（在最近这么松的模式下）。

**Comment by mikezang** [comment]
谢谢回答。另外想问一下，在进行checksum的同时能否开始下载下一个？

**Comment by Kyle-Kyle** [comment]
你可以随时下载多个文件。所以在checksum的时候也是可以下载的。

**Comment by mikezang** [comment]
Can you tell me how to do? remove option "-j 1 "?

**Comment by Kyle-Kyle** [comment]
Ooops. I almost forget that option. You are correct. That's the option you want to remove.

**Comment by mikezang** [comment]
But your last commit message said "download files one by one so that downloads won't be killed when several tasks are going concurrently", what does that mean?

**Comment by mikezang** [comment]
I have another question, is it possible to use functions in your extensions to create a Python script as a downloading tool?

**Comment by Kyle-Kyle** [comment]
Em. If you are going to write a downloading tool in python, it will be much easier than this extension. This javascript stuff drives me crazy.
So, you can, and it is easy. But you need to read the code, and it may be a pain.

**Comment by Kyle-Kyle** [comment]
我用的也是mac。并没有遇到过这种情况。感觉应该是你的网络不太稳定。如果遇到应该是只能重启，反正断点续传，问题也不是太大。
我觉得你如果要写python脚本的话，这个能很好的解决。
