### ISSUE TITLE
GLink is NULL!(chrome version 69.0.3497.100 & baidudl plugin version 2.0.6)

### ISSUE THREAD

**Issue by chentao38324** [Kyle-Kyle/baidudl#133]
GLink is NULL!(chrome version 69.0.3497.100 & baidudl plugin version 2.0.6)

**Comment by heindrix** [comment]
yes. i think baidu have changed their method to verify downloads. because i've tried different tools such like this : https://greasyfork.org/zh-CN/scripts/39504-百度网盘直接下载助手-直链加速版 and this tool : http://pandownload.com/
nothing worked anymore.

**Comment by Parampaa** [comment]
confirmed not working either with the latest chrome and baidudl plugin, even with the greasyfork script

**Comment by Kyle-Kyle** [comment]
No. Not just about download verification, it is totally broken without the app.

**Comment by sugark24** [comment]
there is a solution to repair baidu DL thank you

**Comment by sugark24** [comment]
?

**Comment by Kyle-Kyle** [comment]
@Parampaa Thank you for pointing out greasyfork. I read its changlog and found better solution.
Now we are able to download without **any** download speed limit!

**Comment by Kyle-Kyle** [comment]
For now, baidu is still updating, you may need to click `refresh` button multiple times to get links.
