### ISSUE TITLE
所有文件全部无法读取下载连接

### ISSUE THREAD

**Issue by louislou123** [Kyle-Kyle/baidudl#134]
百度网盘中所有的文件10月15日都无法获取链接，打开插件可以看到文件列表，选择之后点击generate没有反应，将文件分享之后用分享链接打开也无法generate出链接。

**Comment by mecyl** [comment]
获取不了链接了

**Comment by Kyle-Kyle** [comment]
百度方面的问题。我试了一下，正常都无法下载。等等吧。明天可能就好了。

**Comment by louislou123** [comment]
我觉得如果百度使用了什么方式来阻止我们获取下载链接的话光等是没用的。。。

**Comment by Kyle-Kyle** [comment]
@louislou123 百度自己的那个app：百度网盘，一样不能用。说明百度自己炸了。

**Comment by zlf179** [comment]
的确是这样 熊爪服务器做了调整 所以等是没用的 必须登录账号才能下载

**Comment by louislou123** [comment]
额。。我只是外行。。不过既然百度自己的app都挂了那就只好先等等了。。另一个插件百度网盘助手还能用但速度也只有几十kb了。。

**Comment by Kyle-Kyle** [comment]
emmm。有点意思。不过百度的调整也不是一次两次了。
我周末看一下，不过可能不会更新，要更新也会是下个星期。（毕竟百度经常调整一个星期然后觉得不行又调回去）

**Comment by raydied4** [comment]
不仅如此，插件都不能用了，我还以为是chrome升级之后的问题

**Comment by sclsj** [comment]
登陆网盘账号后也用不了。连直接下载（网页版，≤1mb小文件）都下载不了。
example: https://pan.baidu.com/s/1miSh3s8#list/path=%2F
screenshot/video: https://scls-my.sharepoint.cn/:f:/g/personal/joyjin_scls-sh_org/EhbllaKFLQZIvgcyhcD4btgBKGimZvvDJ1L4K02x53vdyw?e=Ldh7kE

**Comment by zlf179** [comment]
> 登陆网盘账号后也用不了。连直接下载（网页版，≤1mb小文件）都下载不了。
> example: https://pan.baidu.com/s/1miSh3s8#list/path=%2F
> screenshot/video: https://scls-my.sharepoint.cn/:f:/g/personal/joyjin_scls-sh_org/EhbllaKFLQZIvgcyhcD4btgBKGimZvvDJ1L4K02x53vdyw?e=Ldh7kE

插件就是根据分享下载做的 而且最近百度做了修改 导致插件不能用了
另外直接下载 也不是这个插件的功能啊

**Comment by hopefully2333** [comment]
现在小文件是能下的，我刚下好一个小的文件，走 web 的方式

**Comment by Kyle-Kyle** [comment]
由于百度仍然在更新（现在，几个小时后就不好说了）。可能需要多次点击refresh按钮来生成链接。当百度方面稳定之后，应该就不需要点击多次了。

**Comment by zlf179** [comment]
我refresch了3次都没发现链接生成啊

**Comment by Kyle-Kyle** [comment]
@zlf179 刚放上商城，应该一个小时候才会生效。最新版本是2.0.7。3次是不够的，因为百度在更新，链接很多时候会失效，等百度更新完就好了（估计几个小时后吧）。

**Comment by zlf179** [comment]
> @zlf179 刚放上商城，应该一个小时候才会生效。最新版本是2.0.7。3次是不够的，因为百度在更新，链接很多时候会失效，等百度更新完就好了（估计几个小时后吧）。我自己是refresh了10-15次才生成的。现在正常。等到你们的白天应该就好了

好吧 我的插件目前还没更新到2.0.7 还是06  那就等等吧
感谢作者 更新

**Comment by mikezang** [comment]
会不会账号被加入还名单而不能使用？

**Comment by Kyle-Kyle** [comment]
@mikezang 不会。放心使用。
