### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by duongabcxyz** [Kyle-Kyle/baidudl#136]
I'm having this issue while trying to download a ROM for my phone, it's baidu-dl version 2.0.7. 
![screenshot 16](https://user-images.githubusercontent.com/19766378/47264635-f46bd480-d544-11e8-8a0b-b27f1fe09af3.png)

**Comment by Kyle-Kyle** [comment]
You have to login first

**Comment by duongabcxyz** [comment]
Thank you, my bad :D
