### ISSUE TITLE
Don't work Method2: RPC download(recommended)

### ISSUE THREAD

**Issue by Z-13** [Kyle-Kyle/baidudl#137]
Don't work this method.
I have empty **GLinks** and **HLinks** fields. The button **DownloadRPC** doesn't work too.

How I can download file without baidu profile?

Thx!

**Comment by Kyle-Kyle** [comment]
You have to login first.

**Comment by Z-13** [comment]
> You have to login first.

ok, but I haven't baidu profile.
Can I download a file without profile?

**Comment by Z-13** [comment]
Thx!

**Comment by sugark24** [comment]
I have exactly the same problem I do not count baidu and glink link are empty

**Comment by sugark24** [comment]
Can I download a file without profile? please help
