### ISSUE TITLE
cant get gl or hl links

### ISSUE THREAD

**Issue by pikopikopikopiko** [Kyle-Kyle/baidudl#138]
cant get gl or hl links both fields are empty

**Comment by Kyle-Kyle** [comment]
You need to login first

**Comment by pikopikopikopiko** [comment]
any idea how to register without phone number??

**Comment by darkred3** [comment]
Doesn't work for me anymore since yesterday.

GLink loads immediately but shows this message:
{"error_code":31326,"error_msg":"user is not authorized, hitcode:107","request_id":6871644600937300XXX}

HLink doesn't load at all.

**Comment by Kyle-Kyle** [comment]
@darkred3 That looks weird. Have you got GLink? And where do you see this error message?

**Comment by rkaas10** [comment]
Me too, I'm new to this app (just downloaded) and when I'm on "my files" page of baidu and I click on the baidu-dl extension, GLinks and HLinks do not appear. I know today there was something with baidu, but is that the reason why the links do not appear?

(For information: I logged in at the Baidu website. And when I copy a GLink I get the next message: This field is empty)

**Comment by darkred3** [comment]
@Kyle-Kyle I get GLinks immediately after loading. Then I copy it and enter the link into a new tab to start the download. After 1-2 seconds this error message appears.
Also, HLinks aren't being generated at all anymore. This all started 2 days ago.

Also after updating to 2.0.8 I get this:
Starting...
getting glink list...
updating glink list
Try to fetch hlinks
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 3
timeout
retry...
try count is: 4
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden

**Comment by Kyle-Kyle** [comment]
Emmm. Interesting. I will try it tonight.

**Comment by Kyle-Kyle** [comment]
@darkred3 fixed. But this time, your download is not anonymous.

**Comment by suikadesu** [comment]
updated extension to 2.0.9, still showing forbidden errors for me. somehow it says it is still trying to get links anonymously:
Refreshing...
initializing share page...
share page main logic starts
getting parameter extra...
getting yunData in share page...
getting glink list...
verification is required
getting glink list...
updating glink list
Try to fetch hlinks
Try to get hlinks when logged in
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden

**Comment by pikopikopikopiko** [comment]
yeap yesterday it was working fine now forbidden

**Comment by citterino** [comment]
Even though I am already logged in on Baidu account, the baidudl extension still tells me to login in to get the hlinks, which is incredibly odd.

Any reason for this?

**Comment by Kyle-Kyle** [comment]
fixed in 2.0.10
