### ISSUE TITLE
为什么有的资源不出现Hlink？

### ISSUE THREAD

**Issue by mikezang** [Kyle-Kyle/baidudl#139]
同一个分享中的某些可以快速下载，可是一部分刷新几十次也不出现Hlink，为什么？有没有办法解决？

**Comment by Kyle-Kyle** [comment]
加入了一部分跟这个问题有关的异常考虑，可以尝试一下。还没有Push到商城。

**Comment by mikezang** [comment]
下载文件很多时不容易记住已经下载过的，能不能保持文件一被加入下载队列的显示信息？

**Comment by Kyle-Kyle** [comment]
已经有了。我前天添加了这一块。

**Comment by mikezang** [comment]
是吗？好像没有看到。

**Comment by Kyle-Kyle** [comment]
你用的是商城版本？那还没更新。

**Comment by mikezang** [comment]
原来如此。

**Comment by mikezang** [comment]
中文说明的连接没有修改。

**Comment by mikezang** [comment]
以前虽然很多时间不到1M的速度，但是可以下载。现在几乎不出现HLinks，有没有办法改善？

**Comment by Kyle-Kyle** [comment]
不到1M...不可能.请用rpcdownload下载.具体方式见使用说明.现在应该可以到带宽上限.
不出link的问题，更新到2.0.8试试.有什么问题可以贴log上来.

**Comment by mikezang** [comment]
不到1m是2.0.6以前，昨晚用最新的2.0.8几个小时测试，没有HLinks出现:(

**Comment by Kyle-Kyle** [comment]
@mikezang 修好了。但是速度不是不限速了。百度估计是看到我在github上的留言了，3-4天就紧急修复了。这是我见过百度效率最高的一次┑(￣Д ￣)┍

**Comment by LEMONed** [comment]
2.0.9 仍然无法 gen 出来任何 hlinks.. 周末挺着急用的，这下完了。

**Comment by mikezang** [comment]
一直显示Trying，没有HLinks，是这个链接https://pan.baidu.com/s/1UMPMHt9uBH_sVnb7jH19mQ

**Comment by mikezang** [comment]
看来百度封死你了，HLinks再也没出现过。

**Comment by Penny1a** [comment]
> 不到1M...不可能.请用rpcdownload下载.具体方式见使用说明.现在应该可以到带宽上限.
> 不出link的问题，更新到2.0.8试试.有什么问题可以贴log上来.

没有HLinks怎么用rpcdownload下载？

Warning: HLinks should be generated before download!

**Comment by Kyle-Kyle** [comment]
在2.0.10已修复
