### ISSUE TITLE
I find that it doesn't work in liebao browser

### ISSUE THREAD

**Issue by Mikoto10032** [Kyle-Kyle/baidudl#14]
when i click the icon, it told me that pan.baidu.com only, but nothing appear.

**Comment by EMLVIRUS** [comment]
try mainstream browser instead: Google chrome, Mozilla Firefox, opera, Vivaldi, cent, etc.

**Comment by Mikoto10032** [comment]
Fine, thank you！

**Comment by Kyle-Kyle** [comment]
it also works on 360 browser..some people claim it also works on  sougou browser but it did not pass my test.

**Comment by Mikoto10032** [comment]
OK, i will choose another browser!

**Comment by EMLVIRUS** [comment]
IMHO, support to such browsers can be really awkward as it's very hard to find stable API support

**Comment by dabenlee** [comment]
I tested Vivaldi, it didn't work.

**Comment by Kyle-Kyle** [comment]
@EMLVIRUS 
Actually, this extension doesn't **support** them. It's only because they are using chromium core which means they **are chrome** to this extension.

**Comment by Kyle-Kyle** [comment]
wait. pan.baidu.com only?
This extension will work only in something like [this](https://pan.baidu.com/disk/home#list/path=%2F&vmode=list) and [this](https://pan.baidu.com/s/1mhEXWmc). (password to the latter link is tbyu)
