### ISSUE TITLE
第十次尝试之后就不动了

### ISSUE THREAD

**Issue by zlf179** [Kyle-Kyle/baidudl#140]
Starting...
getting glink list...
updating glink list
Try to fetch hlinks
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden
Glink生成了 但是Hlink迟迟没有生成 是从自己网盘生成的分享链接

**Comment by bullWing** [comment]
遇到同样的问题，而且Glink也无法下载

**Comment by Sheldonsuckz** [comment]
Can confirm that I am getting the same error. Doesn't matter whether I use a VPN, Chinese Baidu account, or an American one.

Refreshing...
initializing share page...
share page main logic starts
getting parameter extra...
getting yunData in share page...
getting glink list...
updating glink list
Try to fetch hlinks
Try to anonymously get hlinks
Try to fetch hlinks
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden
retry...
try count is: 10
Forbidden
Forbidden

![Error](https://i.imgur.com/eTLG6jc.png)

**Comment by Kyle-Kyle** [comment]
嗯。本来是利用了百度的一个bug可以不限速下载的，看来是紧急修复了。昨晚还能用的。
这个问题我也修好了。我现在网不好，只知道能下，速度最少1M/s。

**Comment by bullWing** [comment]
> 嗯。本来是利用了百度的一个bug可以不限速下载的，看来是紧急修复了。昨晚还能用的。
> 这个问题我也修好了。我现在网不好，只知道能下，速度最少1M/s。

![image](https://user-images.githubusercontent.com/23136277/47487925-fea80e80-d875-11e8-80ce-d0e944822024.png)
貌似文件大点的就不显示 Hlink

**Comment by bullWing** [comment]
![image](https://user-images.githubusercontent.com/23136277/47488059-36af5180-d876-11e8-9644-b324dc1596ad.png)
等了几分钟没出来，小文件几秒就刷出来了

**Comment by louislou123** [comment]
这么说百度盯上你的github了，这下不好办了啊（笑）

**Comment by Sheldonsuckz** [comment]
Any file over 100 MB will not have a Hlink generated. Hopefully they turn a blind eye to this and we can fix it soon.

**Comment by Sheldonsuckz** [comment]
After waiting for an hour my link finally loaded and I was able to get good speeds.
![Success](https://i.imgur.com/94bQD1e.png)

**Comment by Kyle-Kyle** [comment]
fixed in 2.0.10
