### ISSUE TITLE
you need to login first

### ISSUE THREAD

**Issue by murath9** [Kyle-Kyle/baidudl#142]
![2018-10-26_3-30-34](https://user-images.githubusercontent.com/44504725/47576840-5e1d2180-d93d-11e8-82e2-9d2b48906f88.png)

**Comment by wsky11** [comment]
Having same issue but I'm unable to create account since country code is not listed. Any ideas?

**Comment by Parampaa** [comment]
This worked for me: http://livejinju.com/how-to-register-baidu-without-mainland-china-number/

**Comment by wsky11** [comment]
I was able to make an account but now the hlink won't appear. Just keep getting "trying"

**Comment by Parampaa** [comment]
Same for me, but regular download link worked perfectly. Read my reply on another thread for details.

**Comment by Kyle-Kyle** [comment]
fixed in 2.0.10

**Comment by kristoffzoghbi** [comment]
I'm using 2.0.10 and still facing this issue

**Comment by Kyle-Kyle** [comment]
@kristoffzoghbi which problem? `You need to login first`? That literally means you need an account to use this extension.

**Comment by kristoffzoghbi** [comment]
@Kyle-Kyle I thought this extension saves you from needing an account to access the file. Anyway, thank you for your response. I managed to create an account using this [link](passport.baidu.com/v2/?reg&overseas=1)

**Comment by Kyle-Kyle** [comment]
@kristoffzoghbi It used to. But after baidu introduced some mitigations, it does not work provide anonymous download anymore.

**Comment by murath9** [comment]
i don't have an account in baidu, i was downloading using baidudl and tampermonkey extensions and script. but now when i try to get downloads links tell me you need to login first?
so, how i can create an account and login ?

**Comment by kristoffzoghbi** [comment]
@murath9 use this [link](passport.baidu.com/v2/?reg&overseas=1) to create an account. It works for any country

**Comment by murath9** [comment]
that's helpful ?
http://livejinju.com/how-to-register-baidu-without-mainland-china-number/

**Comment by murath9** [comment]
> @murath9 use this [link](passport.baidu.com/v2/?reg&overseas=1) to create an account. It works for any country

thanks but it's show me page error 404 ..
this is not the web page you are looking for.

**Comment by Kyle-Kyle** [comment]
@murath9 I updated the link so it does not 404 now

**Comment by murath9** [comment]
> @murath9 I updated the link so it does not 404 now

![capture](https://user-images.githubusercontent.com/44504725/48014197-6c7df100-e126-11e8-9901-64d9eb6de824.PNG)
still same problem in this [link](https://passport.baidu.com/v2/?reg&overseas=1)
![capture](https://user-images.githubusercontent.com/44504725/48014251-8c151980-e126-11e8-8335-5a9041f1299e.PNG)

**Comment by Kyle-Kyle** [comment]
@murath9 Try it again.

**Comment by murath9** [comment]
Thank you. the registration is done .. i will try to download now

**Comment by murath9** [comment]
there is new problem? : 
Starting...
getting glink list...
updating glink list
Try to fetch hlinks
Try to get hlinks when logged in
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden
