### ISSUE TITLE
Error The link that it generates does not work

### ISSUE THREAD

**Issue by Superhackman** [Kyle-Kyle/baidudl#143]
![captura de pantalla 17](https://user-images.githubusercontent.com/27593140/47598828-a2251c00-d967-11e8-862f-9190f4d179e6.png)

**Comment by Superhackman** [comment]
@Sheldonsuckz I am not in the United States, I am and I currently live in Panama

**Comment by citterino** [comment]
@Sheldonsuckz What is the region you are using for VPN to successfully download? You said you have tried with Indonesian IP but that doesn't work anymore. And it seems like the OP has tried with China without any success, which is odd to me.

**Comment by Sheldonsuckz** [comment]
I let my friend in Indonesia use my account and he was able to download just fine. I also used a VPN in Paris and I was able to download off of that too. The only problem I have is downloading from the US since it gives me a 403 forbidden error when doing so.

**Comment by Superhackman** [comment]
@citterino @Sheldonsuckz What makes me weird is that it gives this unauthorized user error with this extension, instead of using the official Baidu application if it allows me to download

**Comment by Superhackman** [comment]
closed why? pandownload working very good

**Comment by Superhackman** [comment]
@Superhackman what? Pandownload Spy?

**Comment by citterino** [comment]
@Sheldonsuckz I have tried several regions for VPN (like Japan, Singapore, Malaysia), but it seems none of them worked. Do you still have any luck with Paris or Indonesia?

**Comment by Parampaa** [comment]
I'm live in Indonesia, using this plugin gives me error 'unauthorized user' (logged in baidu account).
Tried using greasyfork script v1.3.2 with logged in account and it works perfectly.
Noticed that generated link is c.pcs.baidu.com which usually d.pcs.baidu.com
Also the redirected link is nbct01.baidupcs.com which unusual for me.

BUT, I got something weird. Trying to change generated link from this plugin (which d.pcs.baidu.com) to c.pcs.baidu.com and guess what? It allow me to download.

![image](https://user-images.githubusercontent.com/9270306/47959855-cc8a6f80-e020-11e8-98d2-9cf471fba7f9.png)

**Comment by wsky11** [comment]
Wow, I changed it to c.pcs and it worked. The speed is incredibly slow but it'll have to do for now.

What's the greasyfork script?

**Comment by citterino** [comment]
@Parampaa I really appreciate you taking your time writing this. I am not too familiar with all the URL magic, but I was wondering why the generated link from baidudl is different than the URL link you have in your IDM? It seems like you have a specified server (in this case nbct01), and then you copied and pasted in a string of random characters from the generated link. Do you mind explaining how to get the final URL that you put into the IDM from the generated link?

**Comment by Kyle-Kyle** [comment]
@Parampaa Thanks for the info. Now it is working again.

**Comment by Kyle-Kyle** [comment]
fixed.

**Comment by Parampaa** [comment]
@wsky11 this script https://greasyfork.org/en/scripts/39504-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B-%E7%9B%B4%E9%93%BE%E5%8A%A0%E9%80%9F%E7%89%88

@citterino the final URL is kind of temporary link that you get from the generated link (d.pcs), it's kind of authorization link (d.pcs) containing many GET parameters that lead to true link/temporary link for your files. The logic is if you are free user and sending authorization link, then baidu will respond download link to slower server. If you have free time, try analyze that greasyfork script for better understanding.

**Comment by wsky11** [comment]
It's back to not working for me even when I change it to c.pcs. So I tried the greasyfork script instead, but I keep getting "Failed to get file ID"

My country is not listed on the overseas registration form so I used a free sms service but that has proved to be unreliable. Anyone else found a solution?

**Comment by citterino** [comment]
@wsky11 Just curious. Why do you need to register for a new Baidu account if you already have an existing Baidu account?

**Comment by wsky11** [comment]
@citterino I keep getting locked out of my account since there's other people logging in using the same number from the free sms site I used to register. I can only log back in once I recover the password but I gotta use that same sms number to get sent a code before I can change it. I've gotten rid of the number from my profile multiple times and added my email instead for verification purposes, but it still doesn't work because I keep getting locked out, and gotta recover the password etc. Hate Baidu :(
