### ISSUE TITLE
不能生成Hlink，Glink生成了但是无法下载

### ISSUE THREAD

**Issue by hopefully2333** [Kyle-Kyle/baidudl#144]
Glink中的链接下载是一个HTML，不能下载到文件。

**Comment by Kyle-Kyle** [comment]
现在确实没办法使用。百度这回的更新是下狠手了的。如果你遇到别的软件还能加速下载，请告诉我，我会更新。

**Comment by hopefully2333** [comment]
那这类插件以后还能用得上吗？

**Comment by srwgin** [comment]
> 现在确实没办法使用。百度这回的更新是下狠手了的。如果你遇到别的软件还能加速下载，请告诉我，我会更新。

https://pandownload.com/
测试下来这个软件登录后 能正常下载 速度1MB有的

**Comment by Kyle-Kyle** [comment]
在2.0.10修复
