### ISSUE TITLE
baidudl doesn't work

### ISSUE THREAD

**Issue by masuods70** [Kyle-Kyle/baidudl#147]
@Kyle-Kyle 
baidudl doesn't work for me
i install baidudl 2.0.9 and run baidudl_rpc and login to pan.baidu.
after click on baidudl icon GLinks show me but after copy and paste links in idm nothing happens and no show zip file for download.
I did not have this problem before and it's about a week that's the problem.
what's the solution?
please help.

Refreshing...
initializing share page...
share page main logic starts
getting parameter extra...
getting yunData in share page...
listing dir...
List dir succeeds
getting glink list...
updating glink list
Try to fetch hlinks
Try to get hlinks when logged in
Try to fetch hlinks
Try to get hlinks when logged in
Try to fetch hlinks
Try to anonymously get hlinks
Try to anonymously get hlinks
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 2
Forbidden
retry...
retry...
try count is: 3
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 5
Forbidden
retry...
try count is: 6
Forbidden
retry...
try count is: 5
6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden
retry...

**Comment by Kyle-Kyle** [comment]
fixed in 2.0.10
