### ISSUE TITLE
will this extension support aria2 rpc？

### ISSUE THREAD

**Issue by skyqty** [Kyle-Kyle/baidudl#15]
Hi, if will be support aria2 that's will be great

**Comment by Kyle-Kyle** [comment]
This is what I thought some time ago. But aria2...well..sucks in some cases and the max threads it support is 16 which is not enough.

Well..To demonstrate my point of view, you can try [this link]("https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B528361645901193%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:A9hgdZLQ1ohRfsnevkyAX7SdpCg%3D&uid=2869107310&time=1501120347&dp-logid=4787263802708455739&dp-callid=0&vuk=2869107310") with aria2 compared with IDM.

**Comment by skyqty** [comment]
I know ..but consider  using OpenWrt, the aria2 is only way

**Comment by Kyle-Kyle** [comment]
If you insist, I'd like to recommend you another project called `baiduExporter` which is much more developer friendly. This extension is more like for muggles(oops).

**Comment by Kyle-Kyle** [comment]
`BaiduExporter` is out of date. They are deploying some useless API.
So aria2 rpc support is on the way.

**Comment by Kyle-Kyle** [comment]
aria2 rpc is supported.
Could you help me test it?

**Comment by mpco** [comment]
Please support aria2 rpc token.

**Comment by skyqty** [comment]
it's fine with aria2 1.32.0, nicely done

**Comment by shikkoku** [comment]
![image](https://user-images.githubusercontent.com/4697177/28883281-6db70bb6-77e0-11e7-84ca-c7f045df5366.png)

有使用说明吗？ any tutorial?

**Comment by shikkoku** [comment]
![image](https://user-images.githubusercontent.com/4697177/28883463-262c5980-77e1-11e7-9ab0-35a07e90c501.png)

出现了一点错误，有教程吗？ any tutorial?

**Comment by Kyle-Kyle** [comment]
@shikkoku It's fixed in 1.3.5. If you don't won't to update, you can use this extension in incognito mode.

**Comment by shikkoku** [comment]
Yes it work fine in incognito mode. 

话说baidudl_rpc_1.3.4_WIN.zip包里的aria2c用的是那个解除线程限制的版本吧？

**Comment by Kyle-Kyle** [comment]
@shikkoku It's the original aria2c. aria2c supports multi-connection per server and multi-source. I just combine them together.

**Comment by shikkoku** [comment]
那么还有一个baidudl_rpc.exe的作用是？

**Comment by Kyle-Kyle** [comment]
@shikkoku For muggles(oops) to enable rpc....

**Comment by shikkoku** [comment]
是为了方便呃……直接省略了配置aria2.conf的配置过程吗？不知道可不可通过计划任务来做到隐藏窗口启动。
Version 1.3.5 is work fine in login mode.

**Comment by Kyle-Kyle** [comment]
@shikkoku You don't need to do configuration, you can simply run `aria2c --enable-rpc --console-log-level=warn`. Other stuff will be sent by the extension itself.

**Comment by shikkoku** [comment]
但我对aria2c不仅仅只用与百度网盘上，也有其他的一些其他网站要用到。

**Comment by Kyle-Kyle** [comment]
@you don't need to, but you can if you want to do configuration
