### ISSUE TITLE
Can't get HLink

### ISSUE THREAD

**Issue by ElitesTeaTime** [Kyle-Kyle/baidudl#156]
Hello. First I want to Thank you for your very good works
I just have a problem with this a few day ago.
Yesterday i tried to download zip files. First I tried to use GLink But error message appeared it's say
 
"{"error_code":31326,"error_msg":"user is not authorized, hitcode:107","error_info":"","request_id":7235395671943868010}"

Second i tried to get HLink but it's not appear. here a message

"Refreshing...
initializing share page...
share page main logic starts
getting parameter extra...
getting yunData in share page...
getting glink list...
verification is required
getting glink list...
updating glink list
Try to fetch hlinks
Try to get hlinks when logged in
Try to anonymously get hlinks
Forbidden
retry...
try count is: 1
Forbidden
retry...
try count is: 2
Forbidden
retry...
try count is: 3
Forbidden
retry...
try count is: 4
Forbidden
retry...
try count is: 5
timeout
retry...
try count is: 6
Forbidden
retry...
try count is: 7
Forbidden
retry...
try count is: 8
Forbidden
retry...
try count is: 9
Forbidden
retry...
try count is: 10
Forbidden"

What Should i do ? Thank you for your attention.

**Comment by jiangqinhua** [comment]
hey I having the same issue in window10, may I know how you solve it ?
strange thing is I can use it in my mac, anyone know why ?
