### ISSUE TITLE
Maybe the button is not very friendly

### ISSUE THREAD

**Issue by leoshuanbao** [Kyle-Kyle/baidudl#16]
Thanks for your kindness help 
But I have a question : In 360 Browser, the button click once ,and the link is ok ,but in chrome browser ,after click the butten ,I could't  find the link.
What' wrong with it ?

Thank you,

Best Regards,
Leo

**Comment by Kyle-Kyle** [comment]
Not sure. Maybe you can click `clearCache` first and try again.

**Comment by leoshuanbao** [comment]
ok，I will try it ,Thanks all the same.
