### ISSUE TITLE
This field is empty

### ISSUE THREAD

**Issue by KhaosChow** [Kyle-Kyle/baidudl#170]
![Snipaste_2019-02-21_21-51-51.png](https://i.loli.net/2019/02/21/5c6eaeec9f23c.png)

在分享页面可以使用，但网盘个人主页就出现“This field is empty”错误。
我已经登录账号；baidudl版本：2.0.12。

**Comment by ericxsun** [comment]
+1

**Comment by Kyle-Kyle** [comment]
先生成链接...左边勾选.右上角点generate

**Comment by ericxsun** [comment]
![image](https://user-images.githubusercontent.com/1772912/53849975-ba333900-3ff4-11e9-9aae-6628e1f8d607.png)

一直卡在 `getting glink list...`

版本：2.0.12

**Comment by KhaosChow** [comment]
> 先生成链接...左边勾选.右上角点generate

谢谢！解决了
