### ISSUE TITLE
[Question] max-concurrent-downloads

### ISSUE THREAD

**Issue by Aidolii** [Kyle-Kyle/baidudl#181]
Why does max-concurrent-downloads (`-j`) have to be set to 1? (`-j 1`)

Is this to not get banned from baidu? I am confused because the settings seem to set the threads to 100, which would be like setting max-concurrent-downloads to 100 (`-j 100`).

**Comment by Kyle-Kyle** [comment]
Those are different things.
max-concurrent-downloads: how many file do you wan to download
thread number: how many connection do you want to open for downloading a single file
