### ISSUE TITLE
vcode required?

### ISSUE THREAD

**Issue by yi-Xu-0100** [Kyle-Kyle/baidudl#19]
在分享页面中打开后显示vcode required... 然后有很多的验证码……不知道怎么弄这个问题，感谢作者这个方便的工具。

我是本来自己登录账号下载的，然后貌似被封了，显示Error: this file has been shared too frequently
所以我分享了我的文件，准备匿名从分享页面获得链接，然后就显示vcode required……背景就是这样了。

对了，那个Dlinks显示NA，所以我无法获得普通链接……
还有的显示：Warning: can't get high speed link

**Comment by yi-Xu-0100** [comment]
个人将那些文件通过不断的更换分享文件夹，后来的刷新，成功刷出了链接，暂时解决问题了。

作者大神要是觉得这个主要还是分享过多造成的错误，就关了这个issue吧，只是感觉报的错不是以前issue提过的……

**Comment by Kyle-Kyle** [comment]
在分享页面是没有dlink的。NA是正常的。
不用插件也会导致需要验证码。这个也是很正常的。

can't get high speed link的话。未确认的错误都会报这个错。可能要研究过才能知道具体是什么原因。

**Comment by yi-Xu-0100** [comment]
这个错误好像都只能在特定情况下出现，昨天那些文件我更换分享文件夹，刷新之后得到了高速链接，所以也就无法重现情景了，下次遇到我截个图吧，不过更换分享文件夹真的很有效果……可以破除原被封账号（提示Error: this file has been shared too frequently）的困境。
