### ISSUE TITLE
新api 401错误

### ISSUE THREAD

**Issue by mapleshadow** [Kyle-Kyle/baidudl#21]
RT，显示分享错误之类。。。。。。。。。。

**Comment by Kyle-Kyle** [comment]
分享错误是文件有问题或者是你的账号有问题。
正确的使用应该是在分享页面进行。
并且。有了新的release。配上了专用下载器。大概速度能有5M/s。

**Comment by mapleshadow** [comment]
新版能发布到chrome store吗？感谢！
PS：我是打开网友的分享，然后点击插件点击gen按钮，报错的，下载我自己网盘文件没试过

**Comment by Kyle-Kyle** [comment]
chrome store已经很久没有更新了。。你不说我都忘了。。
网友的分享不需要按generate就应该会出现hlink。generate需要登录。
下载器只有github上有。

**Comment by mapleshadow** [comment]
晕，怪不得，原来我用的都是老版本。。。。。。。。。。。。。。
chrome store很有必要，因为不需要开开发者模式

**Comment by nuomi1** [comment]
刚刚自动更新了，然后 Hlinks 下载失败。
[example](https://d11.baidupcs.com/file/ad86843010b329fb92b5cac0025b7883?bkt=p3-0000ef698da3abbf8c8a6cea89eaa2d5e1e1&fid=4228331065-250528-647644469313865&time=1501473743&sign=FDTAXGERLBHS-DCb740ccc5511e5e8fedcff06b081203-8hS0aq7FA4pTNWKCoWh0uCke39E%3D&to=71&size=1084935623&sta_dx=1084935623&sta_cs=4&sta_ft=rar&sta_ct=6&sta_mt=3&fm2=MH,Yangquan,Netizen-anywhere,,beijing,cmnet&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000ef698da3abbf8c8a6cea89eaa2d5e1e1&sl=76480590&expires=8h&rt=sh&r=455725345&mlogid=4905320497310700099&vuk=282335&vbdid=-&fin=62+-+%E6%98%AF%E6%88%91%E6%9C%80%E5%A5%BD%E7%9A%84%E5%B0%8D%E6%89%8B.rar&fn=62+-+%E6%98%AF%E6%88%91%E6%9C%80%E5%A5%BD%E7%9A%84%E5%B0%8D%E6%89%8B.rar&rtype=1&iv=0&dp-logid=4905320497310700099&dp-callid=0.1.1&hps=1&csl=80&csign=ZMLyV6T0L9zkkwFfMOo%2F4sxc4LA%3D&so=0&ut=6&uter=4&serv=0&by=themis) 提示 `{ "error_code":31064, "error_msg":"xcode expire time out error" }`。

顺便，File name 是乱序的，用着比较麻烦。

**Comment by xesygao** [comment]
更新了1.1.4
{ "error_code":31064, "error_msg":"xcode expire time out error" }

**Comment by qwerttaa** [comment]
@nuomi1  @xesygao  你们俩这个报错我没有遇到，114版

给一下出错的分享文件我试试

**Comment by xesygao** [comment]
@qwerttaa 私人文件不方便分享，目前我就发现那个文件有问题
还发现一个bug，就是切换帐号后显示的文件内容还是上一个帐号的

**Comment by nuomi1** [comment]
@qwerttaa 是获取的 Hlinks 访问后返回这段错误的 json。

另外 1.1.4 获取的 Dlinks 和旧版的 Hlinks 的 URL 构造差不多？

**Comment by Kyle-Kyle** [comment]
这个错误我见过。可是是在之前的开发版本中。1.1.4的时候我没有遇到过。可以把生成的链接和文件链接发上来看一下吗

**Comment by nuomi1** [comment]
链接: https://pan.baidu.com/s/1nvdYI6H 密码: 2agx

[Dlinks](https://d.pcs.baidu.com/file/276d8fefb933b3377d836448dadd8ceb?fid=4228331065-250528-1087435498388258&time=1501498498&rt=pr&sign=FDTAERVC-DCb740ccc5511e5e8fedcff06b081203-DO4uMnW9uH%2BhV%2FrfwyoYSui%2Brlk%3D&expires=8h&chkv=1&chkbd=1&chkpc=&dp-logid=4911965737470515582&dp-callid=0&r=730826258)

[Hlinks](https://d11.baidupcs.com/file/276d8fefb933b3377d836448dadd8ceb?bkt=p3-000093195d9664902ca8a9d76ca85b73c313&fid=4228331065-250528-1087435498388258&time=1501498550&sign=FDTAXGERLBHS-DCb740ccc5511e5e8fedcff06b081203-xUG7xfRWFnyRCUVOTPKBv7OEFuI%3D&to=71&size=1096872041&sta_dx=1096872041&sta_cs=2&sta_ft=rar&sta_ct=6&sta_mt=3&fm2=MH,Yangquan,Netizen-anywhere,,beijing,cmnet&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=000093195d9664902ca8a9d76ca85b73c313&sl=76480590&expires=8h&rt=sh&r=103012689&mlogid=4911979685937757745&vuk=282335&vbdid=-&fin=51+-+%E5%8F%AA%E6%98%AF%E7%9B%A1%E5%85%A8%E5%8A%9B%E6%89%93%E6%AF%8F%E4%B8%80%E5%A0%B4%E6%AF%94%E8%B3%BD.rar&fn=51+-+%E5%8F%AA%E6%98%AF%E7%9B%A1%E5%85%A8%E5%8A%9B%E6%89%93%E6%AF%8F%E4%B8%80%E5%A0%B4%E6%AF%94%E8%B3%BD.rar&rtype=1&iv=0&dp-logid=4911979685937757745&dp-callid=0.1.1&hps=1&csl=80&csign=ZMLyV6T0L9zkkwFfMOo%2F4sxc4LA%3D&so=0&ut=6&uter=4&serv=0&by=themis)

**Comment by Kyle-Kyle** [comment]
确认这是个bug。
会尽快修复。

**Comment by Kyle-Kyle** [comment]
排序错误是正常的。插件暂时没有添加排序功能。

**Comment by Kyle-Kyle** [comment]
错误的原因是模拟匿名登录失败。可能影响的面有点广。

**Comment by Kyle-Kyle** [comment]
@xesygao 还显示上一个账号的可以点击清除缓存。

**Comment by Kyle-Kyle** [comment]
已更新。请大家再测一下。如有问题请发文件和生成链接。方便测试。

**Comment by nuomi1** [comment]
@Kyle-Kyle 1.1.6 依然失败。

链接: https://pan.baidu.com/s/1pLfW7vd 密码: imhc

**Comment by Kyle-Kyle** [comment]
@nuomi1 文件被删除了。

**Comment by nuomi1** [comment]
@Kyle-Kyle 链接: https://pan.baidu.com/s/1pLqLRMN 密码: ynjz

刚看完就删了，抱歉……

**Comment by Kyle-Kyle** [comment]
@nuomi1 我这里很正常。。你试试最新版？

**Comment by Kyle-Kyle** [comment]
由于太多人报这个错。新插件中将原来的hlink（和油猴脚本一样）改为glink重新上线。
比较：
glink: 速度不稳定。但一定可以下载且不报错；
hlink: 速度快但链接不一定可用。

解决方法：使用aria2 rpc下载。速度快且稳定。

**Comment by hilent** [comment]
@Kyle-Kyle 这两天不管是什么文件都是cant't share this file，hlink和glink都是空的。版本是1.3.4
刚才又测试了一下，分享页面可以，自己的网盘不行，是账号问题吗？

**Comment by Kyle-Kyle** [comment]
@hilent baidudl_rpc闪一下就消失了？那说明出bug了。然而我并不怎么用windows..自己在虚拟机上测试没有问题。。你可以抓到错误信息告诉我是啥么

**Comment by Biercenter** [comment]
@hilent @Kyle-Kyle 
应该是路径里有空格或者中文，我之前也是这样，换一个路径好了

**Comment by hilent** [comment]
@Kyle-Kyle @Biercenter 闪得太快了，不过还是被我发现了，嘿嘿
大概提示的是“D:/program ”不是内部命令，也不是应用程序
不是因为路径有中文，是因为路径有空格。。。我的路径是“D:\Program Files\baidudl_rpc_1.3.4_WIN”
之前用green chrome也出现了类似的问题。
改到“D:\soft\baidudl_rpc_1.3.4_WIN”后，正常了~

**Comment by Kyle-Kyle** [comment]
文件夹的名字从来没有过中文和空格。。我重新编译一次发上去好了。。
