### ISSUE TITLE
更新之后用FDM下载，提示Authorization required

### ISSUE THREAD

**Issue by xliez** [Kyle-Kyle/baidudl#24]
1.别人分享的文件页面会出现，保存到自己盘里再下载也会，但之前转存的文件下载不会出现
2.无论是否登陆账号都会出现
3.之前的版本无此现象，今天早上更新后出现

在此先感谢开发者！

**Comment by Kyle-Kyle** [comment]
暂时的解决方法是重新生成。
新版本更新了链接的生成方式。两个测试者均没有碰到异常。不过这个错误是有可能出现的。
我明天研究一下。

**Comment by Kyle-Kyle** [comment]
Duplicate of #23

**Comment by Kyle-Kyle** [comment]
已更新。请测试。谢谢

**Comment by xliez** [comment]
1. 小体积的文件，可以不调用云盘客户端直接用浏览器下载的文件，用插件没问题
2. 对于300MB以上，强制调用云盘客户端的文件，依然会提示Authorization required

**Comment by xliez** [comment]
刚开始以为是文件大小关系，但又多测试了好几次发现不是这样。
还是会出现同样的问题。
而且有的文件点击插件图标没有反应，console报如下信息：
`
injection.js?_=1501560263110:27 Uncaught ReferenceError: dir is not defined
    at injection (injection.js?_=1501560263110:27)
    at injection_listener.js?_=1501560263111:36
`

**Comment by Kyle-Kyle** [comment]
@xliez 发开版本已修复

**Comment by Kyle-Kyle** [comment]
@xliez 插件更新了获取链接的方式。之前你测的时候我还在开发。所以有点不稳定。
现在麻烦你再试一下。出现bug时， 如果可以的话请提供一下链接。

**Comment by xliez** [comment]
你好，需要认证的问题我这里还存在。
你可以试下我测试的文件
 http://pan.baidu.com/s/1boFW815    52eb

这个版本打开插件的速度比原先快多了！

**Comment by Kyle-Kyle** [comment]
@xliez 整个文件我1.1.4版和最新版都下载完了。没遇到这个问题。
原因未知。不过可以试试重新生成一条链接。

**Comment by xliez** [comment]
好的，我再多试试。
