### ISSUE TITLE
最近更新挺频繁，可以考虑使用travis ci构建

### ISSUE THREAD

**Issue by qwerttaa** [Kyle-Kyle/baidudl#25]
https://travis-ci.org/

一点儿建议，省里省时，自动化

主要是看项目主最近更新频繁，也看到有的小白不会手工安装插件，所以。。。

**Comment by Kyle-Kyle** [comment]
我看了一下travis-ci。似乎像是一个自动帮助build和测试的服务。挺有意思的。（不过相同情况下我更倾向于用docker）
但是问题在这个project是个插件。不需要build也没法在一台server上进行测试。就算在server上过了。不同的网络环境和操作系统环境也可能导致不同的结果。
所以我觉得travis对这个project没有什么帮助。
可能我对travis不够了解。如果有什么说错了希望能够指正
