### ISSUE TITLE
新的RPC用不了啊

### ISSUE THREAD

**Issue by vyronjo** [Kyle-Kyle/baidudl#27]
本来在用1.1.3（第一版）的RPC的，前几天还能用的，昨天开始就用不了了。提示是can' get high speed url list或者是aria2c is not running on port 6800
然后1.3.4（第二版）的RPC打开直接闪退。。

**Comment by Kyle-Kyle** [comment]
1.3.5已经修复。如果不会打包升级的话请在匿名模式下使用。

**Comment by qwerttaa** [comment]
135版，用rpc还不如idm快呢

**Comment by Kyle-Kyle** [comment]
@qwerttaa ????这不科学。原理上rpc的速度至少要是idm的2倍以上。可以发截图和分享链接吗

**Comment by qwerttaa** [comment]
我是在https://pan.baidu.com/disk/home#list/path=%2F&vmode=list目录下的，没有分享那几个文件（甲方的文件，工作用，不方便分享）

idm有2.5m左右，rpc600k。。。不是一个文件，是几个文件，我开始用rpc下，很慢，换idm后嗖嗖的

**Comment by qwerttaa** [comment]
- 395e6c我这儿有必要更吗？

**Comment by Kyle-Kyle** [comment]
@qwerttaa 没必要更。
很神奇。我不太理解出现的这种情况。

**Comment by vyronjo** [comment]
@Kyle-Kyle 哪里有135啊？release没看到，google store 也还是134

**Comment by Kyle-Kyle** [comment]
@vyronjo 在github的历史里面搜。。。

**Comment by vyronjo** [comment]
@Kyle-Kyle 噢~扩展程序大概知道怎么更新了，那RPC怎么弄。。是要用IDLE运行吗

**Comment by vyronjo** [comment]
@Kyle-Kyle 扩展程序安装后版本显示是2.0.0，ID是ID： omopgeklcjdokplmpjikmlipilicccfi
可是获取不了Hlinks，一直显示loading(小框显示或者在文件列表的左下角显示)

**Comment by Kyle-Kyle** [comment]
@vyronjo 2.0.0是正在重构的第二版。。还没写完呢。。
1.3.5在这里
https://github.com/Kyle-Kyle/baidudl/tree/5807fdb0a2d31c29d886a5743db73bc3dc6396f2

**Comment by vyronjo** [comment]
@Kyle-Kyle 了解，能用了，感谢。

**Comment by qq361168780** [comment]
希望增加rpc自定义 远程ip与端口 可以实现导出到服务器远程下载

**Comment by Kyle-Kyle** [comment]
@qq361168780 请单独开一个issue

**Comment by vania988** [comment]
你好，请问rpcdownload 在页面里不显示没有这个选项如何解决？只能copy 链接在复制到aria2里，感觉好麻烦。。

**Comment by Kyle-Kyle** [comment]
@vania988 什么版本。请附截图和插件的console输出

**Comment by vania988** [comment]
![2017-08-05 12 41 18](https://user-images.githubusercontent.com/26437046/28992904-69e40582-79db-11e7-8545-2142872cce52.png)
1.3.4版本

**Comment by shikkoku** [comment]
@vyronjo Chrome商店上的版本没有更新到1.3.5。你要用就用github上的吧。

**Comment by shikkoku** [comment]
@qq361168780 #26
