### ISSUE TITLE
Error: this file has been shared too frequently

### ISSUE THREAD

**Issue by qwerttaa** [Kyle-Kyle/baidudl#28]
一连续剧70多集。。。

web端直接分享提示您今天分享太多了，24小时后再试吧。。。。

连续剧的目录可以获取到hilinks，但是不能RPC下载。。。

无解了。。。。。。

**Comment by qwerttaa** [comment]
p.s. 前两天rpc下载不如idm我找到原因了。。。我自己的问题。。。。。。。

**Comment by Kyle-Kyle** [comment]
这个bug在第二版框架中会修复。。第一版。我放弃了。。。写的太乱了。

**Comment by qwerttaa** [comment]
好的，辛苦了

**Comment by hibem** [comment]
同样问题，出去玩了几天，回来后都获取不到链接。

**Comment by vyronjo** [comment]
建议这种电视剧的资源（一个文件夹含多个文件的）直接自己手动分享文件夹，然后进入分享页面，就会自动生成所有的HLinks了，如果你逐个逐个文件去generate HLink的话，就会出现分享过频的情况了。

**Comment by Kyle-Kyle** [comment]
@vyronjo 新框架中这部分已经是这么写好了。但是新框架还没写完。。
