### ISSUE TITLE
rpc，必须要用baidudl_rpc_1.X.X_WIN.zip里的EXE?能不能自己配置aria2c的设置

### ISSUE THREAD

**Issue by lzh890208** [Kyle-Kyle/baidudl#30]
能不能加个Svip选项，可能镜像加速对超级会员没什么用，因为servers.txt里面的替换主机部分并不是100%都能连，可能反而比单主机下载慢
提示can' get high speed url list，并不下载
如果用
baidudl_rpc_1.1.3_WIN.zip是main.exe
baidudl_rpc_1.3.4_WIN.zip是baidudl_rpc.exe
两个是都要还是？只运行后面版本的baidudl_rpc.exe

**Comment by Kyle-Kyle** [comment]
可能比单主机下载慢： 修改源码里面的最大线程数限制。暂时是164（因为我的版本的aria2c超过这个数字就会报错）。改成一个特别大的数字就能保证速度超过单主机下载。

can't get high speed url list：我也很疑惑为什么会有这个错误。临时性解决方案在1.3.5里面有。其实就是如果报错就只用servers.txt。理想状态下应该是百度会提供16个最佳主机。

1.3.4或1.3.5的插件用1.3.4版本的baidudl_rpc
