### ISSUE TITLE
Error: can't get dlinks

### ISSUE THREAD

**Issue by walasix** [Kyle-Kyle/baidudl#31]
如题，插件出现错误提示Error: can't get dlinks；
而且，为什么我点插件里的RPCDownload没有任何反应？没有开始下载啊。。复制链接用FDM可以下载

**Comment by walasix** [comment]
找到相关issue了， #27 现在就是需要下载1.3.5，但是没搞明白怎么下载。。另外，匿名模式是什么意思啊

**Comment by Kyle-Kyle** [comment]
@walasix 我翻译错了。无痕模式

**Comment by walasix** [comment]
@Kyle-Kyle 浏览器的匿名模式？请问release里面没有的话，最新版怎么下载？没搞懂

**Comment by Kyle-Kyle** [comment]
@walasix 商场已经更新到最新的了

**Comment by tufu9441** [comment]
我遇到了同样的问题，安装了最新版。无论是不是无痕模式，点击插件图标后都会提示这个错误

**Comment by Kyle-Kyle** [comment]
@tufu9441 请问是1.3.5吗？1.3.5已经没有这个错误了。

**Comment by tufu9441** [comment]
是的，从商店安的，然后又试了直接clone的。不知道是不是我使用的姿势不对？我是进入百度网盘后，勾选中想下载的文件前面的方框，然后直接点击右上角插件的图标。

**Comment by Kyle-Kyle** [comment]
@tufu9441 请附上控制台的输出我看一下。谢谢

**Comment by tufu9441** [comment]
![](https://i.imgur.com/oKcEIK1.jpg)

您看一下，不知提供的是否符合要求。

**Comment by Kyle-Kyle** [comment]
@tufu9441 你看到的错误是can't get dlink?

**Comment by tufu9441** [comment]
是的。

2017年8月27日 +0800 14:18 Kyle Zeng <notifications@github.com>，写道：

**Comment by walasix** [comment]
@Kyle-Kyle 在商店下载了，谢谢
@tufu9441 你好，想请教一下，怎么从GitHub页面下载不在release里的最新版啊？（clone最新版）需要额外的软件么？

**Comment by qwerttaa** [comment]
@walasix 不需要什么软件，直接https://github.com/Kyle-Kyle/baidudl/archive/master.zip 解压之后把extension打包，或者直接把文件夹拽到扩展里

**Comment by Kyle-Kyle** [comment]
@tufu9441 不好意思。我看了输出。不知道为什么会出现这个错误。

**Comment by tufu9441** [comment]
我昨天是在macbook上试的，今天在一台Windows 10的电脑上同样提示这个错误，如图：

![image](https://user-images.githubusercontent.com/6790361/29764669-a04a63c8-8c0a-11e7-895e-236da0cc3b03.png)

**Comment by tufu9441** [comment]
我发现前几天无法正常使用的情况是我在百度网盘的根目录点击了插件图标，然后就会报错，但如果进入到一个文件夹中再点，就能够正常生成链接了。
