### ISSUE TITLE
希望加入自定义导出IP与端口

### ISSUE THREAD

**Issue by qq361168780** [Kyle-Kyle/baidudl#32]
希望加入导出到 vps/路由器上 的aria2

**Comment by leenchan** [comment]
对对对... 强烈需求！

**Comment by Kyle-Kyle** [comment]
第二代框架里会有。过段时间会出

**Comment by qq361168780** [comment]
作者你用了什么黑科技导出获得的资源数比另外一个插件多。。

**Comment by Kyle-Kyle** [comment]
@qq361168780 哪个插件有这个功能？我猜应该是我的user-agent不一样吧。windows只提供8个。mac提供16个。

**Comment by Kyle-Kyle** [comment]
1.4.0已支持
