### ISSUE TITLE
Error: can' get high speed url list

### ISSUE THREAD

**Issue by SelenLin** [Kyle-Kyle/baidudl#33]
这个是怎么回事

**Comment by Kyle-Kyle** [comment]
请更新到1.3.5

**Comment by Kyle-Kyle** [comment]
或使用无痕模式

**Comment by walasix** [comment]
@Kyle-Kyle 请问怎么更新到1.3.5？从哪里可以下载？

**Comment by walasix** [comment]
@Kyle-Kyle 请问怎么更新到1.3.5？从哪里可以下载？

**Comment by liu246542** [comment]
@walasix 谷歌商店里还没有更新到1.3.5版本，如果需要最新版本的，可以采取以下步骤（chrome浏览器）：
1. 下载baidudl源代码，如果有安装git的话，直接用`git clone https://github.com/Kyle-Kyle/baidudl`命令下载，如果没安装git，直接点击网页上的`clone or download`按钮，选择`download zip`按钮直接下载，并解压。
2. 打开chrome浏览器的扩展程序页面，点击开发者模式，选择`加载已解压的的扩展性程序`，选择`extension`文件夹，导入即可使用。

**Comment by hilent** [comment]
@Kyle-Kyle 1.3.5一直在用开发者模式加载解压的文件夹，chrome每次打开会提示请停用以开发者模式运行的扩展程序，baidudl的图标就会一直闪啊闪。。纠结很久了，换回1.3.4下载不了，继续用1.3.5就每次都受困扰，能不能劳烦您将1.3.5版本更新至chrome商店一下~谢谢~

**Comment by Kyle-Kyle** [comment]
已更新
