### ISSUE TITLE
这个插件不会被百度屏蔽了把

### ISSUE THREAD

**Issue by ASHESZheng** [Kyle-Kyle/baidudl#34]
这个插件不会被百度屏蔽了把？打开插件。生成glink和hlink后没用发现按钮rpcdownload。结果审查元素时看到<button ng-click="download($index)" ng-hide="x.isdir" class="ng-hide">RPCDownload</button>明显是有的，再看样式发现了一个    display: none !important;，取消掉了之后按钮出现了，但点击无反应，怎么解决

**Comment by shikkoku** [comment]
要用1.3.5版本。请确认你在使用的插件版本。

**Comment by Kyle-Kyle** [comment]
文件夹暂时是不能rpcdownload的

**Comment by shikkoku** [comment]
@Kyle-Kyle 现在的master分支还是能正常用的版本吧？

**Comment by Kyle-Kyle** [comment]
@shikkoku 是
