### ISSUE TITLE
老是提示pan.baidu.com only

### ISSUE THREAD

**Issue by cnjn** [Kyle-Kyle/baidudl#35]
这个插件如果使用crx安装或直接安装解压文件的话，只能用一会，过一会就总提示“pan.baidu.com only”
然后即使移除重装都不能解决，只能去chrome商店重新下载，可是chrome商店的插件，一但停止VPN，又会因无法联网而提示“扩展程序已损坏”，简直逼死我了，

用个360都没有这么多的问题

**Comment by vyronjo** [comment]
你看看你登陆的是pan.baidu.com还是yun.baidu.com，这两个都能登录到网盘，但是插件只对前者有效

**Comment by cnjn** [comment]
我是用的pan.baidu.com，无论怎么刷新都没法使用，只有谷歌商店的才稳定，用crx或解压文件时用了几次后都会提示这个

**Comment by bc419149681** [comment]
你用什么浏览器，我用QQ浏览器9.6.4也出现这个问题，换回9.6.3就可以了

**Comment by Kyle-Kyle** [comment]
可以附上console的输出和插件console的截图吗?

**Comment by Kyle-Kyle** [comment]
有没有可能是你下载的crx的问题。我自己打包的crx放在别的电脑上好像也没事。

**Comment by bc419149681** [comment]
http://c3.pcs.baidu.com/rest/2.0/pcs/superfile2?method=upload&app_id=250528…DEzQRxNrUYmcIcb6A%3D%3D&logid=MTUwMzU0NjU5NzM0OTAuOTYxMTI4MDcxMTA0MDYzMQ== Failed to load resource: the server responded with a status of 400 (Bad Request)

**Comment by Kyle-Kyle** [comment]
@bc419149681 你这条链接不是用来下载的。链接本身有问题。
