### ISSUE TITLE
生成链接后点击RPC DOWNLOAD会提示“Warning: aria2c is not running on port 6800”

### ISSUE THREAD

**Issue by DEVGX** [Kyle-Kyle/baidudl#36]
生成链接后点击## _RPC DOWNLOAD_会显示

> aria2c is not running on port 6800

请问是什么原因导致的？求解.

**Comment by Kyle-Kyle** [comment]
没开baidudl_rpc

**Comment by DEVGX** [comment]
打开了，显示READY，但马上就会有不兼容提示，在网盘里也还是一样的情况……系统是 win10 1703 15063.540，谢谢解答.

**Comment by DEVGX** [comment]
看来是我的描述不清了，抱歉。不兼容提示指的是运行baidudl_rpc时，先会有READY提示，再会有不兼容提示。如图：
![qq 20170824114612](https://user-images.githubusercontent.com/31159457/29648732-48fad49a-88c2-11e7-857a-9a0503eec6ee.png)
再者，网盘里一样的情况指的是会像之前一样，百度网盘里会显示：aria2c is not running on port 6800.如图：
![qq 20170824114712](https://user-images.githubusercontent.com/31159457/29648780-91d57134-88c2-11e7-8a58-85651f5d2662.png)
事实上，此时baidudl_rpc已经运行了，运行时状况就是上图所示。
感谢解惑

**Comment by Kyle-Kyle** [comment]
这个软件是64bit的。如果你的电脑是32bit的话。只能说抱歉了。
