### ISSUE TITLE
"error_code":31064, "error_msg":"xcode expire time out error" 

### ISSUE THREAD

**Issue by ghost** [Kyle-Kyle/baidudl#37]
master分之下最新版

hlink就这样儿了

https://pan.baidu.com/s/1kUNPiZ1
rxv3

**Comment by Kyle-Kyle** [comment]
这是个已知但是暂时没有解决的错误。请暂时使用glink

**Comment by redapple0204** [comment]
@Kyle-Kyle 但问题是glink下载速度太垃圾了啊.....只有100k/s

**Comment by Kyle-Kyle** [comment]
今天自己下载文件。遇到了这个问题。解决方法已找到。

**Comment by qwertccc** [comment]
@Kyle-Kyle 能修复最好：D

**Comment by Kyle-Kyle** [comment]
引入filter后解决。
