### ISSUE TITLE
prcdownload 按钮失效

### ISSUE THREAD

**Issue by srwgin** [Kyle-Kyle/baidudl#38]
这几天突然开始 按prcdownload 没反应
用的商店的最新版本1.3.5
应该是1.3.5的问题
Latest commit 44d2872  25 days ago @Kyle-Kyle Kyle-Kyle simple wrap for aria2c
用这个版本就正常了

**Comment by Kyle-Kyle** [comment]
可以附上console的输出信息吗？网页的console和插件的console

**Comment by Maddaxman** [comment]
**插件console**
angular.min.js:123 TypeError: Cannot read property 'length' of undefined
    at controller.js:146
    at get_all_hlinks (aria2_rpc.js:53)
    at $http.post.then.$scope.message (controller.js:144)
    at angular.min.js:134
    at m.$digest (angular.min.js:145)
    at m.$apply (angular.min.js:149)
    at l (angular.min.js:102)
    at XMLHttpRequest.A.onload (angular.min.js:107) "Possibly unhandled rejection: {}"
(anonymous)	@	angular.min.js:123
(anonymous)	@	angular.min.js:95
g	@	angular.min.js:134
$digest	@	angular.min.js:145
$apply	@	angular.min.js:149
l	@	angular.min.js:102
A.onload	@	angular.min.js:107

**浏览器console**
**①**
GET http://pan.baidu.com/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-sharelinkpic&l…e=0&web=1&app_id=250528&logid=MTUwMzgwNzQ4NDE5NTAuMjM4NTEwMTQ3MTYyMDgzODU= net::ERR_BLOCKED_BY_CLIENT
send	@	??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
ajax	@	??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
getAdResoucre	@	??disk-share-cdn/widget/log/log_1318206.js,disk-share-cdn/pkg/page-ui_53a8cbc.js,disk-share-cdn/js/…:4
(anonymous)	@	link?shareid=315544391&uk=2039596288&errno=0&errmsg=Auth Login Sucess&&bduss=&ssnerror=0:233
(anonymous)	@	link?shareid=315544391&uk=2039596288&errno=0&errmsg=Auth Login Sucess&&bduss=&ssnerror=0:253

**②**
GET http://pan.baidu.com/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-sharelinkpic&l…e=0&web=1&app_id=250528&logid=MTUwMzgwNzQ4NDMyNDAuMzQ1NTcyODQ0NjQ3ODQxMg== net::ERR_BLOCKED_BY_CLIENT
send @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
ajax @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
getAdResoucre @ ??disk-share-cdn/widget/log/log_1318206.js,disk-share-cdn/pkg/page-ui_53a8cbc.js,disk-share-cdn/js/…:4
errorCallback @ ??disk-share-cdn/widget/log/log_1318206.js,disk-share-cdn/pkg/page-ui_53a8cbc.js,disk-share-cdn/js/…:4
error @ ??disk-share-cdn/widget/log/log_1318206.js,disk-share-cdn/pkg/page-ui_53a8cbc.js,disk-share-cdn/js/…:4
l @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:4
fireWith @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:4
r @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
n @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5 GET http://pan.baidu.com/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-text&list%5B0%…e=0&web=1&app_id=250528&logid=MTUwMzgwNzQ4NDk5NjAuNDIxNzc3MTM1NTQzNzYxNA== net::ERR_BLOCKED_BY_CLIENT
send @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
ajax @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
pt.(anonymous function) @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
getJSON @ ??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
getUnionData @ disk.header.js?t=1499170226279:15
init @ disk.header.js?t=1499170226279:15
yunHeader.union @ disk.header.js?t=1499170226279:15
renderHeaderDom @ disk.header.js?t=1499170226279:25
t @ disk.header.js?t=1499170226279:25
(anonymous) @ disk.header.js?t=1499170226279:25

**③**
??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5 GET http://pan.baidu.com/feproxy/ad/list?list%5B0%5D%5Bid%5D=web-text&list%5B0%…e=0&web=1&app_id=250528&logid=MTUwMzgwNzQ4NDk5NjAuNDIxNzc3MTM1NTQzNzYxNA== net::ERR_BLOCKED_BY_CLIENT
send	@	??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
ajax	@	??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
pt.(anonymous function)	@	??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
getJSON	@	??base-cdn/pkg/base_cfa5d98.js,system-core-cdn/pkg/all_f6add5b.js,disk-share-cdn/pkg/system_04c6ba5…:5
getUnionData	@	disk.header.js?t=1499170226279:15
init	@	disk.header.js?t=1499170226279:15
yunHeader.union	@	disk.header.js?t=1499170226279:15
renderHeaderDom	@	disk.header.js?t=1499170226279:25
t	@	disk.header.js?t=1499170226279:25
(anonymous)	@	disk.header.js?t=1499170226279:25

**Comment by Kyle-Kyle** [comment]
@Maddaxman 1.3.6已修复。请测试。

**Comment by srwgin** [comment]
OK 1.3.6测试正常 等商店版更新
