### ISSUE TITLE
如何用aria管理

### ISSUE THREAD

**Issue by share18x** [Kyle-Kyle/baidudl#39]
我想用Aria的web端管理下载暂停，如何实现？

**Comment by Biercenter** [comment]
chrome 插件商店找yaaw for chrome

**Comment by Kyle-Kyle** [comment]
https://ziahamza.github.io/webui-aria2/
http://yaaw.ghostry.cn/
主机设置成127.0.0.1.端口设置成6800.
不支持ssl加密
