### ISSUE TITLE
下载后期速度下滑至0

### ISSUE THREAD

**Issue by foxzld** [Kyle-Kyle/baidudl#4]
30M联通宽带，下载初期速度客观，1M/S左右，70%左右就开始逐步下滑，下载到80左右就over再也下不动了。。。。aria2测试3遍都一样。。。
FDM试了下，最快不过1M/S，一般400-600K/S，到60%停掉了。。。暂停再开始会再下一段然后又0K/S
，反复循环。。。最多到90%就彻底over了
700M左右视频文件

**Comment by Kyle-Kyle** [comment]
可以麻烦你生成一个链接并且把文件分享给我吗？

**Comment by foxzld** [comment]
https://pan.baidu.com/s/1eS3l92i

**Comment by Kyle-Kyle** [comment]
aria2c均速1.1M/s.FDM均速800K/s.两个都下载完了。初步怀疑与网络环境有关。这个对话我关了。如果你觉得有疑问的话还可以再开

**Comment by Kyle-Kyle** [comment]
<img width="408" alt="screen shot 2017-05-20 at 8 55 34 pm" src="https://cloud.githubusercontent.com/assets/13167376/26275995/3c2d9788-3da0-11e7-9215-eb0c03832804.png">
<img width="638" alt="screen shot 2017-05-20 at 8 55 42 pm" src="https://cloud.githubusercontent.com/assets/13167376/26275997/4378d20a-3da0-11e7-8f6b-6e0becd12731.png">
<img width="235" alt="screen shot 2017-05-20 at 9 04 36 pm" src="https://cloud.githubusercontent.com/assets/13167376/26275998/466ca9f0-3da0-11e7-9304-892f122155b5.png">
