### ISSUE TITLE
建议：aria2c 用bat批处理文件启动

### ISSUE THREAD

**Issue by chenhaowen01** [Kyle-Kyle/baidudl#40]
aria2c 用bat批处理文件启动，看起来要比用 python 更方便，也不用 pyinstaller 来生成可执行文件，体积也更小。
另外，aria2可以使用配置文件吧，方便用户定制。

**Comment by Kyle-Kyle** [comment]
要考虑跨平台的能力吧。(其实是因为我自己用的是mac。。根本不会写bat...)

**Comment by chenhaowen01** [comment]
各平台个别分发啊，反正aria2c也不可能二进制跨平台，总要分别打包的。*nix用shell脚本启动，Windows用bat文件启动。
好吧，其实我也不太会写bat，但是这需求不复杂，只要吧aria2c启动就行了，写一写还是没问题的

**Comment by srwgin** [comment]
windows写个 start.vbs 开机启动不就好了
`createobject("wscript.shell").run "D:\software\aria2c\aria2c.exe --conf-path=aria2c.conf",vbhide
wscript.quit`

**Comment by shikkoku** [comment]
@srwgin Windows 建立一个计划任务就可以了。也不用vbs。

**Comment by Kyle-Kyle** [comment]
终于写了..原来其实就两行的事情。
