### ISSUE TITLE
Error: this file has been shared too frequently

### ISSUE THREAD

**Issue by houshuheng** [Kyle-Kyle/baidudl#42]
好多文件都出现这种情况 怎么解决啊

**Comment by Kyle-Kyle** [comment]
等一天就好了。
这个问题下个版本会修复。不过要等一段时间。

**Comment by houshuheng** [comment]
等了几天都不行 而且好像越多越多文件都是这样了 无论是否转存到自己网盘 都有这个提示
期待更新 谢谢

**Comment by Kyle-Kyle** [comment]
这就有点不科学了。不转存到自己的网盘不应该出这个提示的。
请问你用的哪个版本？

**Comment by houshuheng** [comment]
用的1.3.5版本 是在chrome商店下载的  chrome版本 60.0.3112.78（正式版本） （32 位）

**Comment by houshuheng** [comment]
我还发现有时候不转存到自己网盘 还没这个提示 转存到自己网盘的 大部分都出现这个提示了

**Comment by Kyle-Kyle** [comment]
不转存到网盘不会有这个提示的。转存到网盘有这个提示的话。可能是你generate按太多了。

**Comment by houshuheng** [comment]
有些是转存必然出现这个提示 不转存 就可以轻松下载 
因为有些资源是网友直接PM分享 不是发分享链接 所以只能先转存到自己网盘 希望能尽快修复

**Comment by Kyle-Kyle** [comment]
很尴尬。百度网盘用的不多。什么是pm分享

**Comment by houshuheng** [comment]
就是百度盘互加好友 直接分享给好友 不是平常那样带链接密码 
在聊天记录里分享给我 我只能转存或者直接下载(自动打开百度客户端)
因为现在发在外面的百度网盘分享很容易被和谐 所以有些都是加好友直接分享的了
![qq 20170917094527](https://user-images.githubusercontent.com/31778658/30517300-4a6f4d5a-9b8d-11e7-96f8-f05ca83423c9.png)
![qq 20170917094537](https://user-images.githubusercontent.com/31778658/30517302-4fa142ec-9b8d-11e7-85c9-690ce3d491d3.png)

**Comment by p520504** [comment]
我觉得是被黑名单了。不知道原理一不一样，听过说有黑名单机制。

这2天新用离线添加的文件无法生成下载
