### ISSUE TITLE
要是有Linux版就好了

### ISSUE THREAD

**Issue by LasyIsLazy** [Kyle-Kyle/baidudl#43]
毕竟最近转战Ubuntu了。

**Comment by Kyle-Kyle** [comment]
这就是个插件。。和Linux有啥关系。。

**Comment by LasyIsLazy** [comment]
我是指下载器，就是baidudl_rpc_1.3.4_WIN.zip这个

**Comment by Kyle-Kyle** [comment]
你都会用ubuntu了。
直接用commandline不就完了。。
sudo apt-get install aria2
aria2c --enable-rpc
就和那个下载器一样了
