### ISSUE TITLE
mac端 打开baidudl未显示“baidudl_rpc is ready...“，网页插件显示“aria2c is not running on port 6800“

### ISSUE THREAD

**Issue by kaylats** [Kyle-Kyle/baidudl#44]
<img width="733" alt="2017-10-11 9 45 17" src="https://user-images.githubusercontent.com/31498821/31418772-afb73588-adfd-11e7-8b55-7bf7eb9530b6.png">
<img width="562" alt="2017-10-11 9 45 50" src="https://user-images.githubusercontent.com/31498821/31418773-afed035c-adfd-11e7-8083-de0d3b9c3678.png">
<img width="452" alt="2017-10-11 9 53 00" src="https://user-images.githubusercontent.com/31498821/31418775-b037db5c-adfd-11e7-9eda-d64953ba837a.png">

我在windows端用这个好好的，mac端不知咋回事，希望大神给解答下。。

**Comment by kaylats** [comment]
都是用的最新版

**Comment by qwerttaa** [comment]
https://github.com/aria2/aria2/releases

下你对应系统版本，运行时候加参数
--enable-rpc 
或者多加几个
--rpc-allow-origin-all=true --max-connection-per-server=10 --split=256

**Comment by qwerttaa** [comment]
链接数跟线程也不是越大越好，看你电脑配置这个意思，256差不多，连接数5到30你看着来吧，百度那服务器也没谱，有的快有的慢

**Comment by qwerttaa** [comment]
@Kyle-Kyle 得空了不忙的话更更啊~之前的bug，求解决：D

**Comment by Kyle-Kyle** [comment]
这个上次有人发邮件问我。我重新写了一个mac版本的baidudl_rpc。
[baidudl_rpc_OSX.zip](https://github.com/Kyle-Kyle/baidudl/files/1375190/baidudl_rpc_OSX.zip)

**Comment by Kyle-Kyle** [comment]
麻烦测试一下。如果没问题的话。我回头更新到release里去。

**Comment by Kyle-Kyle** [comment]
@qwerttaa 之前的bug太多了。。你说的是哪个。很多问题要在第二代框架里解决了。然后现在有点忙。

**Comment by kaylats** [comment]
@Kyle-Kyle mac用了这个版本，管用了！谢谢啦！🙏
@qwerttaa 也谢谢你热心解答啦！

**Comment by qwerttaa** [comment]
@Kyle-Kyle 我是看你新框架下现在还是8月的，一直没动

先忙，得空儿了再弄

现在这些bug都有办法变通解决，除了麻烦点儿，不算彻底不能用

**Comment by shikkoku** [comment]
希望不要等到二代框架未开发完百毒就已经封堵了😂
