### ISSUE TITLE
不知道有没有办法获取服务器端的文件hash

### ISSUE THREAD

**Issue by qwertccc** [Kyle-Kyle/baidudl#46]
最近下片儿经常下坏不知道为什么，看着看着就爆音、马赛克了

不知道百度这里能不能获取文件的hash，比如md5，sha1一类的

有些片子是ed2k或者磁链离线过去的，这个还好说，一比较hash就知道文件坏了，重新下就得了

现在主要是有些文件只有百度网盘下载方式，你下了以后你也不知道是不是hash一致文件没毛病。。。。这个就比较苦恼了

所以。。。

**Comment by Kyle-Kyle** [comment]
好建议。百度有提供md5。回头加上

**Comment by qwerttbb** [comment]
还是期盼你得空儿拾掇拾掇新框架，哈哈哈

**Comment by Kyle-Kyle** [comment]
2.0.0已加入。
