### ISSUE TITLE
360极速匿名状态无法使用

### ISSUE THREAD

**Issue by hilent** [Kyle-Kyle/baidudl#47]
本来是老版本，内核是30的，点击rpcdownload没反应（baidudl_rpc.exe已打开，显示ready）
然后觉得可能是内核太老不支持，就升级最新版了，内核55，还是没反应，如图：

http://ww4.sinaimg.cn/large/0060lm7Tly1fknc44b236j30ql0iv0ud.jpg

补充下，就是这里显示ready，然后软件上一直是baidudl_rpc is ready...，点击rpcdownload，两边都没反应，还是这个样子

———————————————分割线————————————————
以上情况全部出现在【未登录账号】的情况，即匿名模式
登陆百度账号后可正常下载
至于是否限速尚未测试。。。因为比较急，所以之前直接用IDM硬刚了，等下完再试试

**Comment by qwertabc** [comment]
你直接弄个cmd调用aria2c

写个记事本，改扩展名到bat或者cmd

内容如下

aria2c.exe --enable-rpc --rpc-allow-origin-all=true --max-connection-per-server=16 --split=512 

然后运行以后你看看提示什么，点击rpcdownload之后这个cmd窗口有什么动静没有

**Comment by Kyle-Kyle** [comment]
这个问题我遇到过。但是后来没办法重现了。

**Comment by Kyle-Kyle** [comment]
现在已经没有匿名下载了。所以close了
