### ISSUE TITLE
不能识别百度企业网盘分享的链接

### ISSUE THREAD

**Issue by qwertccc** [Kyle-Kyle/baidudl#49]
https://eyun.baidu.com/s/3kVIzHcV

密码3131

这种eyun开头的地址目前不能识别

**Comment by Kyle-Kyle** [comment]
从来没有接触过企业盘。所以开发的时候没有考虑。
而且我看了一下。企业盘和普通的网盘的接口不太一样。所以可能之后也不会支持。抱歉。
