### ISSUE TITLE
无法获取下载链接

### ISSUE THREAD

**Issue by lakehumin** [Kyle-Kyle/baidudl#50]
现在已经没法生成链接了，不是更新了吗

**Comment by Kyle-Kyle** [comment]
没有遇到不能生成链接的情况。请附上截图并说明具体情况

**Comment by doracl** [comment]
补充一下，多点几次还是生成了（-^-）
![image](https://user-images.githubusercontent.com/11531880/33702512-f8afa480-db5e-11e7-92c9-6979af8d721d.png)

**Comment by Kyle-Kyle** [comment]
比较大的可能是比较慢，等一会儿就好了（百度你变了。以前你不是这样的）
