### ISSUE TITLE
Install dev branch and it keep loading

### ISSUE THREAD

**Issue by Oh-Git** [Kyle-Kyle/baidudl#51]
How to get ver2.0 (dev) works in my chrome?
It was successfully installed as Chrome extention, when open a Baidu link, select the file to be dl, click baidudl, it prompts loading forever.
Thanks,

**Comment by Kyle-Kyle** [comment]
It is still under development.
Sorry about that.

**Comment by Oh-Git** [comment]
Thanks, Hope it will be out soon.
