### ISSUE TITLE
Error: cant't share this file

### ISSUE THREAD

**Issue by bsbrother** [Kyle-Kyle/baidudl#55]
文件夹全部, 大多数文件都可以generate link, 很少文件不可以
怎么解决？谢谢！

**Comment by Kyle-Kyle** [comment]
1.收藏到自己的云盘里。
2.clear cache然后刷新页面。打开插件等链接自动生成

**Comment by Kyle-Kyle** [comment]
这是两种解决方法

**Comment by bsbrother** [comment]
1. 收藏到自己的云盘里
   能给具体步骤吗？
2. clear cache然后刷新页面。打开插件等链接自动生成
   链接自动生成大部分， 但个别为空。 点generate all 仍为空

**Comment by wobsuhiren** [comment]
1.在分享页面，点击转存到自己的网盘。我也不知道怎么跟你描述这个操作。。。。
2.单独点空行后面的generate，下面会有提示。过会应该就有了
要还不行你就接着艾特作者吧....

**Comment by bsbrother** [comment]
1.在分享页面，点击转存到自己的网盘。
  我是在自己网盘中(https://pan.baidu.com/disk/home#list/path=%2F&vmode=list)操作的
2. .单独点空行后面的generate，下面会有提示:
  Error: cant't share this file
 要还不行你就接着艾特作者吧?
 意思是换个magnet 或torrent种子重下?

谢谢您及时回复!

**Comment by wobsuhiren** [comment]
Error: cant't share this file 这句话翻译过来就是无法分享这个文件。。。
不然你就等一天再试吧。
第一条是作者提出来的解决方法，适用于打开别人分享的链接，你这个情况不适用，不用看了。
 另：我不是作者，你不用这么客气。

**Comment by bsbrother** [comment]
艾特作者 = @ author = email he/she?

**Comment by vyronjo** [comment]
一天内分享过多就不能分享了。
又或者是该文件就是分享不了（你懂的）
你试试自己分享能不能分享出去
又或者如果你是从别人的分享那里转存的，直接在分享页面下载就好了 不用再另外生成分享链接

**Comment by Kyle-Kyle** [comment]
can't share this file??
厉害了。这个报错是未知的异常。你用无痕模式试试能不能下载。
可以给个链接吗？从来没见过

**Comment by vyronjo** [comment]
@Kyle-Kyle 有的 当文件本身禁止分享的时候就会这样了

**Comment by p520504** [comment]
@Kyle-Kyle 这东西会不会触发百度黑名单？以前通过用外链说有黑名单机制。

这2天新用离线添加的文件无法生成下载，旧的文件却可以
