### ISSUE TITLE
“Error: this file has been shared too frequently” 怎么破？？

### ISSUE THREAD

**Issue by nod518** [Kyle-Kyle/baidudl#6]
大神你好，插件很牛逼，但下了10几个文件后就提示Error: this file has been shared too frequently，不能gen high speed link了，我等了一天好像还是不行唉，不知道要隔多久才能再用。

**Comment by Kyle-Kyle** [comment]
很快就可以了。我自己也被封了一天多。没事的。
最好不要用一键生成。因为生成的太快了。很容易被百度封。
我之后可能会加一个隔一秒生成。这样不容易被封。
