### ISSUE TITLE
自动跳转到主目录bug

### ISSUE THREAD

**Issue by jigsaw1314** [Kyle-Kyle/baidudl#61]
一用这个插件就会跳到主目录，什么情况？

**Comment by Kyle-Kyle** [comment]
可以具体描述一下情况吗。在什么页面。做了什么操作。

**Comment by fuwu1245** [comment]
意思应该是在自己的网盘主页，随便点开一个文件夹，比方说`A`，然后点击插件以下载`A`文件夹里的某些文件，这个时候，页面会刷新，然后回到`A`目录的上级，即网盘的根目录
个人感觉这个问题不算是什么问题，倒是最近生成的链接在aria2GUI中下载会断掉，或者直接没法下载，针对某些大型文件而言，测试了一个900M的文件，暂不清楚原因在哪一部分。。
100多M的倒是可以正常下载

**Comment by Kyle-Kyle** [comment]
抱歉。我试了5个文件夹40个不同文件。没有遇到这个情况。程序中没有跳转页面这个操作。可能是遇到了什么未知的错误，baidu进行了自动跳转。
@jigsaw1314 建议在分享界面使用插件

**Comment by Kyle-Kyle** [comment]
@fuwu1245  你说的问题我知道。是baidu方面的针对。修改UA有一定效果。可是我做过测试，还是会断，所以没有commit。
断开后使用aria2c断点续传可以解决。大概在5次内能够成功进入稳定下载的状态。

**Comment by qwertccc** [comment]
最近确实有两个问题，一个是爱断，一个是连接没有以前多，下载速度慢了一倍，一次多下几个文件才能跑满带宽

**Comment by wobsuhiren** [comment]
@Kyle-Kyle  麻烦问一下多线程下载大文件，视频文件还好，特别是压缩包，下载全是文件损坏。我用winrar修复也是失败，电脑上也没装百度云。
这个问题我知道是百度的问题，我用IDM多线程下载也是损坏。 这个问题有什么办法避免或修复吗？

**Comment by Kyle-Kyle** [comment]
@wobsuhiren 新的问题可以开一个新的issue，不然找不到。有人汇报过可以手动修复，但是我目前找不到了。

**Comment by smilebox** [comment]
我现在也有这样的问题，有什么办法可以解决么？

**Comment by Kyle-Kyle** [comment]
已解决。
