### ISSUE TITLE
Can't generate link with baidudl on chrome

### ISSUE THREAD

**Issue by djonixu** [Kyle-Kyle/baidudl#62]
Hi,
Since last night, I can't generate link with baidudl on chrome. How to solve it?

Regards,
Djoni Xu

**Comment by Kyle-Kyle** [comment]
Could you please provide some information, such as error message or screenshot?

**Comment by djonixu** [comment]
After I click generate, it's came ready on the buttom, but I can't get generate link on link coloum.
Regards,Djoni Xu 

    Pada Selasa, 16 Januari 2018 10:17, Kyle Zeng <notifications@github.com> menulis:
 

 Could you please provide some information, such as error message or screenshot?—

**Comment by Kyle-Kyle** [comment]
What's the message? ready? or error: xxxx?

**Comment by djonixu** [comment]
Hi Kyle,The message just 'ready' but link of file not appear. Not any error message. So I don't know how to solve it.
Thanks,Djoni Xu

 

    Pada Selasa, 16 Januari 2018 10:24, Kyle Zeng <notifications@github.com> menulis:
 

 What's the message? ready? or error: xxxx?—

**Comment by Kyle-Kyle** [comment]
I have encountered this problem before but have no luck to repeat it.
You may try to use this extension in Incognito window. Hope it will work.

**Comment by djonixu** [comment]
I do it in incognito, but can't get link too. 

    Pada Selasa, 16 Januari 2018 10:50, Kyle Zeng <notifications@github.com> menulis:
 

 I have encountered this problem before but have no luck to repeat it.
You may try to use this extension in Incognito window. Hope it will work.—

**Comment by mrcotter** [comment]
Same problem here. In my own baidu pan space, after click generate, the message only showed "ready" but no link displayed.

**Comment by setarehlady** [comment]
same problem here too. It was working fine yesterday, but today I only get this error:
Error: cant't share this file

**Comment by Kyle-Kyle** [comment]
OK. I checked it, it looks like a new mitigation. I'm looking into it now.

**Comment by Kyle-Kyle** [comment]
#63

**Comment by Kyle-Kyle** [comment]
Could you help me test the new version? But this will make your account be limited to 10K/s.

**Comment by djonixu** [comment]
it's work, but slowly

**Comment by Kyle-Kyle** [comment]
@djonixu you could use RPC download which should be expected to download much faster.
