### ISSUE TITLE
Baidu(百度) be evil again

### ISSUE THREAD

**Issue by offwalk** [Kyle-Kyle/baidudl#63]
Thanks Kyle-Kyle.
Today download files from netdisk(pan.baidu.com) need login(for aria2 just Cookies name BDUSS).
so baidudl would unable to generate links without BDUSS.
and for none VIP or svip users would be limited speed 10k when reach about 5-10G for the next 7-10 days.
Fuck Baidu Lee.

**Comment by Kyle-Kyle** [comment]
Looking into it now.

**Comment by Kyle-Kyle** [comment]
Amazing! Baidu totally has removed anonymously download!
You want to download? Login first!

OK. Currently, it's not clear whether account will be banned or not after fixing the extension.

**Comment by offwalk** [comment]
I guess Baidu would put u (baseon your login UK) in it's blacklist  which limited download speed 10k/s for about a week, when u download more than 10G.After a week ,u can download 10G and in blacklist again.
that's it.
hope u fix it soon.

**Comment by Kyle-Kyle** [comment]
@offwalk I agree with you. But this time, baidu did something more than that. I tried to download some normal files without login and I was rejected. I got 403 error. Cool though.

**Comment by Kyle-Kyle** [comment]
This problem should be solved in lastest version. However, this extension does not support anonymous download anymore.

**Comment by offwalk** [comment]
by the way, i found 2 situation to download anonymously. url [https://pan.baidu.com/s/1eQgR2d8#list/path=%2F&page=1]
Ⅰ	batch download as a pack.zip.
https://www.baidupcs.com/rest/2.0/pcs/file?method=batchdownload&app_id=250528&zipcontent=%7B%22fs_id%22%3A%5B%22905921728191785%22%5D%7D&sign=DCb740ccc5511e5e8fedcff06b081203:fJn%2FPakINVysV1UyAlQbxL3Ov2M%3D&uid=3892955562&time=1516181616&dp-logid=364861765775055913&dp-callid=0&from_uk=3892955562

Ⅱ	jpg file original view(原图) is work too.
https://d.pcs.baidu.com/file/09f409504412d036427f22c61c868049?fid=3892955562-250528-313825485313320&time=1516094831&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-prdW3D7n7YNw5lbDDyU9tAc%2FXho%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=364758433175397302&dp-callid=0&r=253425794&sh=1

**Comment by Kyle-Kyle** [comment]
As I remember, batch download is slow and no way to do multithreading download.
Original view is interesting, maybe it can be applied to other file types like rar.

**Comment by setarehlady** [comment]
I don't live in China and cannot register. Is there no way to download anonymously anymore?

**Comment by Kyle-Kyle** [comment]
@setarehlady I'm sorry to say, but for now, no.

**Comment by setarehlady** [comment]
too bad. Thank you anyway for the extension. It was very useful.

**Comment by offwalk** [comment]
@ Kyle-Kyle 	batch download's speed is 100-300 k/s.
 aria2 would download aborted with errorcode=8,
but other download utility supported multithreading work fine,such as  ADM(Android) can reach 1M/s(9 threads).

**Comment by srwgin** [comment]
@offwalk 
try this https://aur.archlinux.org/packages/aria2-fast/

**Comment by Kyle-Kyle** [comment]
@offwalk I tried it, you are correct. There is something wrong with aria2c. batch download works fine in IDM.

**Comment by Gslw** [comment]
If you fix it, can you upload Chrome Store? I always fail to install it manually...
