### ISSUE TITLE
无法生成下载链接

### ISSUE THREAD

**Issue by iceJourney** [Kyle-Kyle/baidudl#65]
baidudl 版本 1.3.5
opera 50.0.2762.58 (PGO)
-----------------------------------
任意分享页面，点击后均无法生成下载链接。

另，听闻pandownloader也挂了。

**Comment by Kyle-Kyle** [comment]
github最近master branch已修复

**Comment by iceJourney** [comment]
ok，通过开发者模式已经加载，还请问此版本的crx什么时候能更新

**Comment by Kyle-Kyle** [comment]
@iceJourney 抱歉。由于一些特殊原因。chrome商场里的baidudl已经不归我管了。所以没办法更新。可能在新框架出来以后会改名再放上chrome store
