### ISSUE TITLE
403:禁止，试了IDM，FDM都不行

### ISSUE THREAD

**Issue by doracl** [Kyle-Kyle/baidudl#66]
generate可以得到链接，但下载是403，最新版本

**Comment by Kyle-Kyle** [comment]
可以试试直接在浏览器访问链接，然后把返回发上来吗

**Comment by doracl** [comment]
浏览器可以下载，但只有几k的速度
![image](https://user-images.githubusercontent.com/11531880/35027709-28926964-fb8d-11e7-8d07-f0d12bd09e21.png)

**Comment by doracl** [comment]
FDM
![image](https://user-images.githubusercontent.com/11531880/35027780-74512d9a-fb8d-11e7-9457-270e5ea41fd0.png)

**Comment by doracl** [comment]
RPC
![image](https://user-images.githubusercontent.com/11531880/35027800-a024569a-fb8d-11e7-95ae-5b49fa8acb9b.png)

**Comment by Kyle-Kyle** [comment]
IDM, FDM的UA已被禁止。刚刚测过。这块是针对UA的封锁。在最新的commit中解决
