### ISSUE TITLE
更新后的baidudl可以解析地址但是推送到rpc下载不了

### ISSUE THREAD

**Issue by mrxiayes** [Kyle-Kyle/baidudl#67]
情况如题

下面是截图

这个是浏览器里链接的返回值
{ "error_code":31326, "error_msg":"anti hotlinking" }

![qq 20180117154110](https://user-images.githubusercontent.com/9998159/35031260-24987834-fb9d-11e7-805f-b36bd2b3957c.png)

**Comment by Kyle-Kyle** [comment]
能不能发一个sample上来看看

**Comment by mrxiayes** [comment]
原地址：https://pan.baidu.com/s/1qZtr3wK

解析后的地址：
glinks链接：
https://d.pcs.baidu.com/file/3e0742ca818327a97af02f1006f31c87?fid=180983796-250528-1099130018604904&time=1516202959&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-Rcd8VWZQ4LJzFffepyKVsnH1%2Bgw%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=393783978317834717&dp-callid=0&r=488786904#0

hlinks链接：
https://d11.baidupcs.com/file/3e0742ca818327a97af02f1006f31c87?bkt=p3-0000d07caf319bc9c1690fef7bed18e327da&fid=180983796-250528-1099130018604904&time=1516202959&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-NNHZmL%2B7g0akN%2B2%2B3Qhm%2BxuyzcM%3D&to=71&size=293051174&sta_dx=293051174&sta_cs=22&sta_ft=rar&sta_ct=7&sta_mt=3&fm2=MH,Nanjing02,Anywhere,,beijing,cmnet&vuk=180983796&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000d07caf319bc9c1690fef7bed18e327da&sl=79364174&expires=8h&rt=sh&r=488786904&mlogid=393783978317834717&vbdid=80396985&fin=2016%E9%AB%98%E6%B8%85%E5%A4%A7%E5%9B%BE.rar&fn=2016%E9%AB%98%E6%B8%85%E5%A4%A7%E5%9B%BE.rar&rtype=1&dp-logid=393783978317834717&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=ZrYEp0Kw88T6GlH%2BZqriClXTn8s%3D&so=0&ut=6&uter=4&serv=0&uc=3003048146&ic=1664372245&ti=5e666840c78f1973e9ff7e592d8881d47307daeb83846f33305a5e1275657320&by=themis

**Comment by Kyle-Kyle** [comment]
新的版本需要登录。不能无痕下载了。

**Comment by mrxiayes** [comment]
我没有用无痕模式 而已一直是登陆百度云账号 下载的 之前也一直是这样 很正常 就是最近两天突然开始出的问题

**Comment by Kyle-Kyle** [comment]
最近baidu出了新的限制。glink出现403是正常的。
你试试hlink。

**Comment by mrxiayes** [comment]
hlink的话 
在浏览器里面显示为：{ "error_code":31064, "error_msg":"xcode expire time out error" }

rpc直接停止，放到迅雷或者fdm提示就是：任务连接超时，无法继续下载

![image](https://user-images.githubusercontent.com/9998159/35081912-c18719ac-fc51-11e7-9cca-fb4b099053d3.png)

![image](https://user-images.githubusercontent.com/9998159/35081972-15aa87c6-fc52-11e7-84ee-62a61d92733c.png)

**Comment by Kyle-Kyle** [comment]
这是个bug。短时间内修复不好。你试试把域名d11.baidupcs.com改成d1.baidupcs.com或者d7.baidupcs.com

**Comment by mrxiayes** [comment]
改成d1或者d7就会变成这样

浏览器下载打开是这样
{ "error_code":31064, "error_msg":"xcode expire time out error" }

fdm打开是这样
![image](https://user-images.githubusercontent.com/9998159/35088766-b425be1c-fc6f-11e7-9d98-6ba7371f4817.png)

rpc下载失败，难道（猜想）是因为经常用第三方下载工具导致账号被百度限制了？

**Comment by qwertccc** [comment]
hlink浏览器可以下，速度90k，rpc不行了，rpc下下来是个html文件

**Comment by doocii** [comment]
2018.01.16 近期百度进行了一系列的打击措施，使用第三方下载器有可能导致账号下载功能被禁用

**Comment by Kyle-Kyle** [comment]
@mrxiayes 不是被限制了。是个已知的bug。短时间内修不好。目前出现的次数比较少。

**Comment by Kyle-Kyle** [comment]
@doocii rpc下来是不是anti-hotlink？

**Comment by Kyle-Kyle** [comment]
@qwertccc rpc下载下来的html里面说anti-hotlink对吗？

**Comment by Kyle-Kyle** [comment]
已确认是百度的mitigation。

**Comment by qwertccc** [comment]
@Kyle-Kyle 不是的，提示“很抱歉，您要访问的页面不存在！”

‘<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <meta content="always" name="referrer">
    <script src="https://ss1.bdstatic.com/5eN1bjq8AAUYm2zgoY3K/r/www/nocache/imgdata/seErrorRec.js"></script>
    <title>页面不存在_百度搜索</title>
    <style data-for="result">
        body {color: #333; background: #fff; padding: 0; margin: 0; position: relative; min-width: 700px; font-family: arial; font-size: 12px }
        p, form, ol, ul, li, dl, dt, dd, h3 {margin: 0; padding: 0; list-style: none }
        input {padding-top: 0; padding-bottom: 0; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box } img {border: none; }
        .logo {width: 117px; height: 38px; cursor: pointer }
         #wrapper {_zoom: 1 }
        #head {padding-left: 35px; margin-bottom: 20px; width: 900px }
        .fm {clear: both; position: relative; z-index: 297 }
        .btn, #more {font-size: 14px } 
        .s_btn {width: 95px; height: 32px; padding-top: 2px\9; font-size: 14px; padding: 0; background-color: #ddd; background-position: 0 -48px; border: 0; cursor: pointer }
        .s_btn_h {background-position: -240px -48px }
        .s_btn_wr {width: 97px; height: 34px; display: inline-block; background-position: -120px -48px; *position: relative; z-index: 0; vertical-align: top }
        #foot {}
        #foot span {color: #666 }
        .s_ipt_wr {height: 32px }
        .s_form:after, .s_tab:after {content: "."; display: block; height: 0; clear: both; visibility: hidden }
        .s_form {zoom: 1; height: 55px; padding: 0 0 0 10px }
        #result_logo {float: left; margin: 7px 0 0 }
        #result_logo img {width: 101px }
        #head {padding: 0; margin: 0; width: 100%; position: absolute; z-index: 301; min-width: 1000px; background: #fff; border-bottom: 1px solid #ebebeb; position: fixed; _position: absolute; -webkit-transform: translateZ(0) }
        #head .head_wrapper {_width: 1000px }
        #head.s_down {box-shadow: 0 0 5px #888 }
        .fm {clear: none; float: left; margin: 11px 0 0 10px }
        #s_tab {background: #f8f8f8; line-height: 36px; height: 38px; padding: 55px 0 0 121px; float: none; zoom: 1 }
        #s_tab a, #s_tab b {width: 54px; display: inline-block; text-decoration: none; text-align: center; color: #666; font-size: 14px }
        #s_tab b {border-bottom: 2px solid #38f; font-weight: bold; color: #323232 }
        #s_tab a:hover {color: #323232 }
        #content_left {width: 540px; padding-left: 121px; padding-top: 5px }
        .to_tieba, .to_zhidao_bottom {margin: 10px 0 0 121px }
        #help {background: #f5f6f5; zoom: 1; padding: 0 0 0 50px; float: right }
        #help a {color: #777; padding: 0 15px; text-decoration: none }
        #help a:hover {color: #333 }
        #foot {position: fixed; bottom:0; width: 100%; background: #f5f6f5; border-top: 1px solid #ebebeb; text-align: left; height: 42px; line-height: 42px; margin-top: 40px; *margin-top: 0; _position:absolute; _bottom:auto; _top:expression(eval(document.documentElement.scrollTop+document.documentElement.clientHeight-this.offsetHeight-(parseInt(this.currentStyle.marginTop,10)||0)-(parseInt(this.currentStyle.marginBottom,10)||0))); }

        .content_none {padding: 45px 0 25px 121px } .s_ipt_wr.bg,
        .s_btn_wr.bg, #su.bg {background-image: none }
        .s_ipt_wr.bg {background: 0 }
        .s_btn_wr {width: auto; height: auto; border-bottom: 1px solid transparent; *border-bottom: 0 }
        .s_btn {width: 100px; height: 34px; color: white; letter-spacing: 1px; background: #3385ff; border-bottom: 1px solid #2d78f4; outline: medium; *border-bottom: 0; -webkit-appearance: none; -webkit-border-radius: 0 }
        .s_btn:hover {background: #317ef3; border-bottom: 1px solid #2868c8; *border-bottom: 0; box-shadow: 1px 1px 1px #ccc }
        .s_btn:active {background: #3075dc; box-shadow: inset 1px 1px 3px #2964bb; -webkit-box-shadow: inset 1px 1px 3px #2964bb; -moz-box-shadow: inset 1px 1px 3px #2964bb; -o-box-shadow: inset 1px 1px 3px #2964bb }
        #lg {display: none }
        #head .headBlock {margin: -5px 0 6px 121px }
        #content_left .leftBlock {margin-bottom: 14px; padding-bottom: 5px; border-bottom: 1px solid #f3f3f3 }
        .s_ipt_wr {border: 1px solid #b6b6b6; border-color: #7b7b7b #b6b6b6 #b6b6b6 #7b7b7b; background: #fff; display: inline-block; vertical-align: top; width: 539px; margin-right: 0; border-right-width: 0; border-color: #b8b8b8 transparent #ccc #b8b8b8; overflow: hidden }
        .s_ipt_wr.ip_short {width: 439px; }
        .s_ipt_wr:hover, .s_ipt_wr.ipthover {border-color: #999 transparent #b3b3b3 #999 }
        .s_ipt_wr.iptfocus {border-color: #4791ff transparent #4791ff #4791ff }
        .s_ipt_tip {color: #aaa; position: absolute; z-index: -10; font: 16px/22px arial; height: 32px; line-height: 32px; padding-left: 7px; overflow: hidden; width: 526px }
        .s_ipt {width: 526px; height: 22px; font: 16px/18px arial; line-height: 22px\9; margin: 6px 0 0 7px; padding: 0; background: transparent; border: 0; outline: 0; -webkit-appearance: none }
        #kw {position: relative;display: inline-block;}
        input::-ms-clear {display: none }
        /*Error page css*/
        .norsSuggest {display: inline-block; color: #333; font-family: arial; font-size: 13px; position: relative; } 
        .norsTitle {font-size: 22px; font-family: Microsoft Yahei; font-weight: normal; color: #333; margin: 35px 0 25px 0; }
        .norsTitle2 {font-family: arial; font-size: 13px; color: #666; }
        .norsSuggest ol {margin-left: 47px; }
        .norsSuggest li {margin: 13px 0; }
        #content_right {
    border-left: 1px solid #e1e1e1;
    width: 384px;
    margin-top: 25px;
    float: right;
    padding-left: 17px;
}
#wrapper_wrapper {
    width: 1212px;
}
.cr-content {
    width: 351px;
    font-size: 13px;
    line-height: 1.54em;
    color: #333;
    margin-top: 6px;
    margin-bottom: 28px;
    word-wrap: break-word;
    word-break: normal;
}
@media screen and (max-width: 1217px) {
    #wrapper_wrapper {
        width: 1002px;
    }
    #wrapper_wrapper #content_right {
        width: 271px;
    }
    #wrapper_wrapper .cr-content {
        width: 259px;
    }
}
.opr-toplist-title {
    position: relative;
    font-size: 14px;
    line-height: 1.29em;
    font-weight: 700;
    margin-bottom: 10px;
}
.opr-toplist-table {
    width: 100%;
    border-collapse: collapse;
    border-spacing: 0;
    font-size: 13px;
}
.opr-toplist-table th,td {
    line-height: 1.54;
    border-bottom: 1px solid #f3f3f3;
    text-align: left;
}
.opr-toplist-table thead th {
    padding-top: 4px;
    padding-bottom: 4px;
    font-weight: 400;
    color: #666;
    white-space: nowrap;
    background-color: #fafafa;  
}
.opr-toplist-table .opr-toplist-right {
    text-align: right;
    white-space: nowrap;
}
.opr-toplist-table td {
    width: 100%;
    font-size: 13px;
    padding-top: 6.5px;
    padding-bottom: 6.5px;
    vertical-align: top;
}
.opr-toplist-table a:hover {
    text-decoration: underline;
}
.opr-index-item {
    display: inline-block;
    padding:1px 0;
    color: #fff;
    width: 14px;
    line-height: 100%;
    font-size: 12px;
    text-align: center;
    background-color: #8eb9f5;
    margin-right: 5px;
}
.opr-index-hot1 {
    background-color: #f54545;
}

.opr-index-hot2 {
    background-color: #ff8547;
}
.opr-index-hot3 {
    background-color: #ffac38;
}
.opr-item-text {
    text-decoration: none;  
}
.opr-toplist-info {
    color: #666;
    text-align: right;
    margin-top: 5px;
}
.opr-toplist-info>a {
    color: #666;
}
    </style>
</head>

<body link="#0000cc">
    <div id="wrapper" class="wrapper_l">
        <div id="head">
            <div class="head_wrapper">
                <div class="s_form">
                    <div class="s_form_wrapper">
                        <a href="//www.baidu.com/" id="result_logo"><img src="//www.baidu.com/img/baidu_jgylogo3.gif" alt="到百度首页" title="到百度首页"></a>
                        <form id="form" name="f" action="//www.baidu.com/s" class="fm">
                            <input type="hidden" name="ie" value="utf-8">
                            <input type="hidden" name="f" value="8">
                            <input type="hidden" name="rsv_bp" value="1">
                            <input type="hidden" name="ch" value="">
                            <input type="hidden" name="tn" value="baiduerr">
                            <input type="hidden" name="bar" value="">
                            <span class="bg s_ipt_wr iptfocus">
                                <input id="kw" name="wd" class="s_ipt" value="" maxlength="255" autocomplete="off" autofocus>
                            </span><span class="bg s_btn_wr">
                                <input type="submit" id="su" value="百度一下" class="bg s_btn">
                            </span>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="s_tab" id="s_tab"><b>网页</b><a href="http://news.baidu.com/ns?cl=2&rn=20&tn=news&word=" wdfield="word">新闻</a><a href="http://tieba.baidu.com/f?kw=&fr=wwwt" wdfield="kw">贴吧</a><a href="http://zhidao.baidu.com/q?ct=17&pn=0&tn=ikaslist&rn=10&word=&fr=wwwt" wdfield="word">知道</a><a href="http://music.baidu.com/search?fr=ps&ie=utf-8&key=" wdfield="key">音乐</a><a href="http://image.baidu.com/i?tn=baiduimage&ps=1&ct=201326592&lm=-1&cl=2&nc=1&ie=utf-8&word=" wdfield="word">图片</a><a href="http://v.baidu.com/v?ct=301989888&rn=20&pn=0&db=0&s=25&ie=utf-8&word=" wdfield="word">视频</a><a href="http://map.baidu.com/m?word=&fr=ps01000" wdfield="word">地图</a><a href="http://wenku.baidu.com/search?word=&lm=0&od=0&ie=utf-8" wdfield="word">文库</a><a href="//www.baidu.com/more/">更多»</a></div>
    <div id="wrapper_wrapper">
        <div id="content_left">
            <div class="nors">
                <div class="norsSuggest">
                    <h3 class="norsTitle">很抱歉，您要访问的页面不存在！</h3>
                    <p class="norsTitle2">温馨提示：</p>
                    <ol>
                        <li>请检查您访问的网址是否正确</li>
                        <li>如果您不能确认访问的网址，请浏览<a href="//www.baidu.com/more/index.html">百度更多</a>页面查看更多网址。</li>
                        <li>回到顶部重新发起搜索</li>
                        <li>如有任何意见或建议，请及时<a href="http://qingting.baidu.com/index">反馈给我们</a>。</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div id="foot">
        <span id="help" style="float:left;padding-left:121px">
            <a href="http://help.baidu.com/question" target="_blank">帮助</a>
            <a href="http://www.baidu.com/search/jubao.html" target="_blank">举报</a>
            <a href="http://jianyi.baidu.com" target="_blank">给百度提建议</a>
        </span>
    </div>
</body>
<script>
(function () {
        var LOGURL = 'https://sp1.baidu.com/5b1ZeDe5KgQFm2e88IuM_a/cm.gif';
        var params = 'type=wwwerror&terminal=www';
        var img = new Image();
        img.src = LOGURL + '?' + params;
    })();
    (function () {
        if(window.recommend && window.recommend.query && window.recommend.query.length > 0) {
            var recommendWrapper = document.createElement('div');
            var recommendHtml = '<div class="cr-content"><div class="opr-toplist-title">' + window.recommend.title + '</div><table class="opr-toplist-table"><thead><tr><th>排名</th></tr></thead>';
            var queryArray = window.recommend.query;
            var itemUrl = '';
            for(var i = 1; i < (queryArray.length+1); i++) {
                itemUrl = '//www.baidu.com/s?word=' + queryArray[i-1].word + '&sa=' + queryArray[i-1].sa + '&tn=' + queryArray[i-1].tn;
                if (queryArray[i-1].rsv_dl) {
                    itemUrl += "&rsv_dl=" + queryArray[i-1].rsv_dl;
                }
                
                if (i < 4) {
                    recommendHtml += '<tr><td><span class="opr-index-hot' + i + ' opr-index-item">' + i + '</span><a target="_blank" href="' + itemUrl +'" class="opr-item-text">' + queryArray[i-1].word + '</a></td></tr>';
                } else {
                    recommendHtml += '<tr><td><span class="opr-index-item">' + i + '</span><a target="_blank" href="' + itemUrl +'" class="opr-item-text">' + queryArray[i-1].word + '</a></td></tr>';
                }
            }
            recommendHtml += '</tbody></table><div class="opr-toplist-info"><span>来源：</span><a target="_blank" href="http://www.baidu.com/link?url=sLR63PtaB7kc3YkTtzDy1k3mbTm1DXDMu-nLcijZx8DmWgOff4lBxqmY-LGDyHqw">百度风云榜</a><span>&nbsp;-&nbsp;</span><a target="_blank" href="http://www.baidu.com/link?url=01vNBVXR2eaJxETl9PI3hcrvKCcwaJIKk5FkpO7l5YI_Q_pC24ogIBoZxI0LAu5oYpAdhRH42nzxAqfui0YnHK">实时热点</a></div></div>';
            recommendWrapper.setAttribute('id', 'content_right');
            document.getElementById('wrapper_wrapper').insertBefore(recommendWrapper, document.getElementById('content_left'));
            var recommend = document.getElementById('content_right');
            recommend.innerHTML = recommendHtml;
        }
})();
(function(){
    var bds = {
        util: {}
    };
    var c = document.getElementById('kw').parentNode;

    bds.util.getWinWidth = function(){
        return window.document.documentElement.clientWidth;
    };

    bds.util.setFormWidth = function(){
        var width = bds.util.getWinWidth();
        if(width < 1217)    {bds.util.setClass(c, 'ip_short', 'add')}
        else                {bds.util.setClass(c, 'ip_short', 'remove')};
    };

    bds.util.setClass = function(obj, class_name, set) {
        var ori_class = obj.className,
            has_class_p = -1,
            ori_class_arr = [],
            new_class = '';

        if(ori_class.length) ori_class_arr = ori_class.split(' ');

        for( i in ori_class_arr) {
            if(ori_class_arr[i] == class_name) has_class_p = i;
        }

        if( set == 'remove' && has_class_p >= 0) {
            ori_class_arr.splice(has_class_p, 1);
            new_class = ori_class_arr.join(' ');
            obj.className = new_class;
        } else if( set == 'add' && has_class_p < 0) {
            ori_class_arr.push(class_name);
            new_class = ori_class_arr.join(' ');
            obj.className = new_class;
        }
    }
    bds.util.setFormWidth();

    if (typeof document.addEventListener != "undefined") {
        window.addEventListener('resize', bds.util.setFormWidth, false);
        document.getElementById('kw').addEventListener('focus', function(){bds.util.setClass(c,'iptfocus', 'add');}, false);
        document.getElementById('kw').addEventListener('blur', function(){bds.util.setClass(c,'iptfocus', 'remove');}, false);
    } else {
        window.attachEvent('onresize', bds.util.setFormWidth, false);
        document.getElementById('kw').attachEvent('onfocus', function(){bds.util.setClass(c,'iptfocus', 'add');}, false);
        document.getElementById('kw').attachEvent('onblur', function(){bds.util.setClass(c,'iptfocus', 'remove');}, false);
    } 

})();


</script>

</html>
’

**Comment by Kyle-Kyle** [comment]
@qwertccc hlink我正在考虑取消。现在似乎没有vip专用的服务器了（也可能只是我找不到）。暂时最好的下载方案就是rpcdownload。

**Comment by qwertccc** [comment]
@Kyle-Kyle 现在获取的hlink浏览器还是可以直接下啊，只是推到aria2里就报错，下来就是个html

**Comment by qwertccc** [comment]
把aria2c伪装成浏览器我试试

**Comment by Kyle-Kyle** [comment]
@qwertccc 最新版本的已经伪装成浏览器了

**Comment by qwertccc** [comment]
@Kyle-Kyle 光插件伪装不行，aria2c客户端也得伪造一下，加一个参数就行

--user-agent=Mozilla/5.0

我已经试了，aria2c加这个参数以后，可以直接推过来下载了，不会再下成html

舒服~

**Comment by Kyle-Kyle** [comment]
@qwertccc 不需要。在插件发包给aria2c-rpc的时候带了一个参数是user-agent。和这个设置是一个道理，并且还能集成到插件中。

**Comment by qwertccc** [comment]
又测试了好几个文件，都可以这么干了

爽

**Comment by qwertccc** [comment]
妥了，牛掰
