### ISSUE TITLE
最近几天都无法生成下载链接

### ISSUE THREAD

**Issue by hyopo** [Kyle-Kyle/baidudl#68]
点击generate，显示Running，一会儿之后就ready，但是没生成链接。
清除过cookie，插件的clean cache也试过，就是不生成。
win10 chrome  63.0.3239.132（正式版本）（64 位）

**Comment by Kyle-Kyle** [comment]
Chrome商店的版本没法更新了。请使用github中的版本

**Comment by hyopo** [comment]
好的~

**Comment by doocii** [comment]
2018.01.16 近期百度进行了一系列的打击措施，使用第三方下载器有可能导致账号下载功能被禁用

**Comment by Kyle-Kyle** [comment]
下载最新的插件https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb?hl=en-GB
请小心使用。账号可能被限速。
