### ISSUE TITLE
下载不能加速了啊

### ISSUE THREAD

**Issue by songwong** [Kyle-Kyle/baidudl#69]
浏览器自带的下载 速度100kb/s 迅雷完全下不动了

**Comment by doocii** [comment]
2018.01.16 近期百度进行了一系列的打击措施，使用第三方下载器有可能导致账号下载功能被禁用

**Comment by Kyle-Kyle** [comment]
下载最新的插件https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb?hl=en-GB
请小心使用。账号可能被限速。
