### ISSUE TITLE
获取文件地址已经失效

### ISSUE THREAD

**Issue by UnaHe** [Kyle-Kyle/baidudl#70]
![image](https://user-images.githubusercontent.com/30680842/35091773-7652727a-fc78-11e7-80ec-fc368868bb3c.png)
文件夹me没问题,但是文件的不行了,前面没多久百度改了响应

**Comment by doocii** [comment]
2018.01.16 近期百度进行了一系列的打击措施，使用第三方下载器有可能导致账号下载功能被禁用

**Comment by vyronjo** [comment]
插件更新了 能获取的。
不过最近还是不要用了，在打压，速度变得有点迷，而且据说还会被封号。

**Comment by UnaHe** [comment]
哎，真是无奈

**Comment by Kyle-Kyle** [comment]
下载最新的插件可以获取链接。https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb?hl=en-GB
请小心使用。账号可能会被限速。
