### ISSUE TITLE
chrome 商店版本： 1.3.5 

### ISSUE THREAD

**Issue by lsnmx** [Kyle-Kyle/baidudl#71]
https://chrome.google.com/webstore/detail/baidudl/mccebkegnopjehbdbjbepjkoefnlkhef

这个安装了谷歌不给用
https://github.com/Kyle-Kyle/baidudl/files/1642980/baidudl_1.4.1.crx.zip

**Comment by x94fujo6rpg** [comment]
下載
https://dl.google.com/dl/edgedl/chrome/policy/policy_templates.zip
解壓

WIN+R 或 對[開始]右鍵>[執行] 輸入gpedit.msc
[電腦設定] > [系統管理範本]>[右鍵]>[新增/移除範本]
簡中
policy_templates\windows\adm\zh-CN\chrome.adm
繁中
policy_templates\windows\adm\zh-TW\chrome.adm

[電腦設定] > [系統管理範本]>[傳統系統管理範本]>[Google]>[Google Chrome]>[擴充功能]
找到[設定擴充功能安裝許可清單]
選擇啟用
要從黑名單上移除的擴充功能ID [顯示]
輸入顯示在 chrome://extensions/ 的baidudl的ID
像是mpgdmaehhamahdfbkfecnhgdjogkdenj
確定後刷新 chrome://extensions/ 即可啟用

現在用其他軟體可能無法下載
chrome單線(極慢) / 推薦使用RPCDownload (aria2) 可多線
aria2報錯無法下載可嘗試添加參數--user-agent=Mozilla/5.0

**Comment by mapleshadow** [comment]
对啊对啊，还请更新chrome商店版本，使用这种开发模式的加载方式，总觉得太奇怪了

**Comment by Kyle-Kyle** [comment]
抱歉。由于一些特殊原因，chrome商店里的插件我没法更新了。之后会考虑自己申请一个账号换个名字上架。

**Comment by Kyle-Kyle** [comment]
@domeafaver rpc server启动失败。
[baidudl_rpc_1.4.2_WIN.zip](https://github.com/Kyle-Kyle/baidudl/files/1655021/baidudl_rpc_1.4.2_WIN.zip)
这个还没测试完。你可以先用着试试。

**Comment by lsnmx** [comment]
@Kyle-Kyle  麻烦上架一个chrome能直接安装不用折腾的吧谢谢

**Comment by Kyle-Kyle** [comment]
https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb
