### ISSUE TITLE
google商店里的可以更新了

### ISSUE THREAD

**Issue by 527440470** [Kyle-Kyle/baidudl#73]
谷歌商店里的可以更新了 用github上的疯狂提示关闭开发者

**Comment by lsnmx** [comment]
还是旧版本啊

**Comment by mapleshadow** [comment]
还是旧版本，1.3.5

**Comment by Kyle-Kyle** [comment]
#71

**Comment by Kyle-Kyle** [comment]
https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb
