### ISSUE TITLE
下载速度不稳定

### ISSUE THREAD

**Issue by hjq1001** [Kyle-Kyle/baidudl#74]
rpc下载已经分享的文件，速度一开始是满速，然后逐渐下降，最后在600kb/s到1.5Mb/s之间波动，这是什么原因

**Comment by Kyle-Kyle** [comment]
这是baidu方面的限制。之后会拿一个vip账号做测试。看看他们是怎么确认vip的，有没有利用的可能。

**Comment by Kyle-Kyle** [comment]
该限制已经被解除。
