### ISSUE TITLE
how to use it in chrome? 

### ISSUE THREAD

**Issue by uruhanzou** [Kyle-Kyle/baidudl#75]
chrome does not allow the installation of baidu 1.4.1 because it is not from its web store

**Comment by Kyle-Kyle** [comment]
#71

**Comment by uruhanzou** [comment]
can you make it in english language :( ?

**Comment by uruhanzou** [comment]
need to login first ? what does that mean ?

**Comment by Kyle-Kyle** [comment]
you need to login into baidu netdisk(baidu wangpan) first to get download link.
Due to baidu's new mitigation, you can not download without login.

**Comment by uruhanzou** [comment]
Is there any other way?

**Comment by Kyle-Kyle** [comment]
@uruhanzou sorry. This is baidu's mitigation, you can't bypass it.

**Comment by Sheldonsuckz** [comment]
Is there anyway to make a new Baidu account? Every time I attempt to make one I get: 百度正在进行系统升级，暂时不能提供服务，敬请谅解

**Comment by Kyle-Kyle** [comment]
@Sheldonsuckz sorry. I think it is out of the scope of this extension. And personally, I don't know how to apply for an account.

**Comment by Sheldonsuckz** [comment]
Thanks for the reply. I mentioned it because I thought a lot of people who use your extension don't actually have Baidu accounts.

**Comment by Rictusempra** [comment]
@Sheldonsuckz that used to work, not now

**Comment by uruhanzou** [comment]
I found the latest way, but I think is very difficult to use. using Proxyee-Down, do you know how to use it?

**Comment by poutine-lament** [comment]
Thanks, your extension works.

Sign up for an accounting using an overseas phone number.

**Comment by Kyle-Kyle** [comment]
download it from chrome store at
https://chrome.google.com/webstore/developer/stats/lflnkcmjnhfedgibjackiibmcdnnoadb?hl=en-GB
