### ISSUE TITLE
error_code 31064 with Glink and Hlink

### ISSUE THREAD

**Issue by i-Grey** [Kyle-Kyle/baidudl#77]
{ "error_code":31064, "error_msg":"xcode expire time out error" }

It works fine yesterday with Glink but I can't use it anymore in today.
I've already logged in. I use extension 1.4.2 right now.

**Comment by Kyle-Kyle** [comment]
if it is from glink, I think it's baidu's problem.

**Comment by Kyle-Kyle** [comment]
#37

**Comment by Kyle-Kyle** [comment]
solved by using Hlink filter.
