### ISSUE TITLE
错误：Exception caught Exception: [download_helper.cc:121] errorCode=1 GID 4753820325266aef is not unique.

### ISSUE THREAD

**Issue by szl0834** [Kyle-Kyle/baidudl#78]
使用RPCDownload 后，aria2关闭后无法打开
出现错误提示
Exception caught
Exception: [download_helper.cc:121] errorCode=1 GID 4753820325266aef is not unique.
清空aria2.session后可以打开

   下面我的config，session文件
dir=C:\Users\szl08\Downloads
log=C:\aria2\aria2.log
input-file=C:\aria2\aria2.session
save-session=C:\aria2\aria2.session
save-session-interval=60
force-save=true
log-level=error

# see --split option
max-concurrent-downloads=5
continue=true
max-overall-download-limit=0
max-overall-upload-limit=50K
max-upload-limit=20

# Http/FTP options
connect-timeout=120
lowest-speed-limit=10K
max-connection-per-server=10
max-file-not-found=2
min-split-size=1M
split=5
check-certificate=false
http-no-cache=true

# FTP Specific Options

# BT/PT Setting
bt-enable-lpd=true
#bt-max-peers=55
follow-torrent=true
enable-dht6=false
bt-seed-unverified
rpc-save-upload-metadata=true
bt-hash-check-seed
bt-remove-unselected-file
bt-request-peer-speed-limit=100K
seed-ratio=0.0

# Metalink Specific Options

# RPC Options
enable-rpc=true
pause=false
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-save-upload-metadata=true
rpc-secure=false

# Advanced Options
daemon=true
disable-ipv6=true
enable-mmap=true
file-allocation=falloc 
max-download-result=120
#no-file-allocation-limit=32M
force-sequential=true
parameterized-uri=true

         下面是我的session文件
http://d1.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://d7.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://nbcache00.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://nbcache03.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://nj02all01.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://yqall02.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://bjbgp01.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://allall01.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://allall02.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	http://d11.baidupcs.com/file/c0345cff4924bf7818a8b2f6fbbdce3f?bkt=p3-1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&xcode=5adc3cc7f987be894c823881520eaf1f657b6ebbbb4055dcdfd1b248e56ae093d2e8fc8000401a3c857a9f09e911e99dda88d2b41f6aa178&fid=2668081893-250528-524619813073017&time=1517554047&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-Qb4sk7uGXu6nOhKMWG0B1GEcaks%3D&to=d11&size=3218603&sta_dx=3218603&sta_cs=8139&sta_ft=rar&sta_ct=7&sta_mt=7&fm2=MH%2CYangquan%2CAnywhere%2C%2Csichuan%2Cct&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=1400c0345cff4924bf7818a8b2f6fbbdce3fca7f31cb000000311cab&sl=79364174&expires=8h&rt=sh&r=657028390&mlogid=756463894816040969&vbdid=-&fin=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&fn=aria2%E6%8E%A7%E5%88%B6%E7%95%8C%E9%9D%A2.rar&rtype=1&dp-logid=756463894816040969&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=3866051599&ic=4064979553&ti=1040a7fdfbe7f41424d4e58e58ba44e0e0bccaa7d9cee4b0&by=themis	
 gid=4753820325266aef
 out=aria2控制界面.rar
 split=160
 max-connection-per-server=16
 min-split-size=1048576
 user-agent=netdisk;2.2.0;macbaiduyunguanjia

**Comment by Kyle-Kyle** [comment]
目测是session方面的设置没有做好，应该和插件没有关系。

**Comment by Kyle-Kyle** [comment]
如果你觉得可能是插件的问题的话可以重开issue，我们可以讨论一下。
