### ISSUE TITLE
只能先放到文件夹再用

### ISSUE THREAD

**Issue by riverai** [Kyle-Kyle/baidudl#8]
只能把目标文件先移动到某个文件夹

直接搜索这个文件然后点击扩展会返回
error,fail to list folder

**Comment by Kyle-Kyle** [comment]
没懂。目标文件是个文件夹？
可以附图或者是console的输出吗？

**Comment by riverai** [comment]
目标文件是单个文件，但是如果我直接搜索它这时候就没法用扩展导出下载。

![default](https://user-images.githubusercontent.com/3251548/27743217-d2e20386-5ded-11e7-861a-5cbd9b7b93af.png)

**Comment by Kyle-Kyle** [comment]
了解了。是因为搜索的问题。下一个补丁会补上

**Comment by riverai** [comment]
谢谢。

**Comment by Kyle-Kyle** [comment]
solved
