### ISSUE TITLE
发现的下载链接不是高速链接

### ISSUE THREAD

**Issue by feverbit** [Kyle-Kyle/baidudl#80]
在网页端直接下载，和用插件获取到的链接是同一个。还是100多k的速度。

**Comment by Kyle-Kyle** [comment]
100多k是对的。因为被封号的人只有10k。

**Comment by Kyle-Kyle** [comment]
使用rpc下载能到6M/s左右。

**Comment by fabiommc** [comment]
@Kyle-Kyle RPC Download for me is slow is using the H links?
I get like 22KB/s - 500KB/s with multiple connections on aria by default rpc add, and it has the problem of stopping downloading completely too. 
If i manually add a G link to Aria2 is downloading way faster.
Other multi thread download managers can max connection too with G links.

Thank you.

**Comment by Kyle-Kyle** [comment]
@fabiommc sorry for the late reply. RPC Download does not use Hlink. RPC Download use something more than Hlink and Glink. It should be super fast and must be faster than Hlink. Could you provide some log info for further investigation?

**Comment by Kyle-Kyle** [comment]
@fabiommc And btw, what version are you using?

**Comment by fabiommc** [comment]
Was using last git version, i will try to use it soon and post logs if same behavior happens.

**Comment by Kyle-Kyle** [comment]
@fabiommc you may try the wip branch which is currently under development and only works on share page

**Comment by Kyle-Kyle** [comment]
This problem is out of date. If you still experience the same problem, feel free to reopen it.
