### ISSUE TITLE
导出的链接无法下载

### ISSUE THREAD

**Issue by shingoxray** [Kyle-Kyle/baidudl#81]
链接导入到aria2里无法下载，还需要导入cookie么？

**Comment by Kyle-Kyle** [comment]
不需要。报的什么错

**Comment by shingoxray** [comment]
跑到NAS的shell里看了下，一开始aria2报证书错误：
[SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate
通过--check-certificate=false参数过去了。
但又报403错误：
Exception: [AbstractCommand.cc:351] errorCode=22 URI=http://www.baidupcs.com/403.html
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
被封禁了？

**Comment by shingoxray** [comment]
试了几个文件，Glinks无法下载，Hlinks可以，但速度有限，开10个线程能到500KB/s。
用的Chrome Store版本1.3.5。

**Comment by Kyle-Kyle** [comment]
嗯。最近百度方面在自己做调整。不是我们这里的问题。
我在3个小时内经历了可以用到不可以用又到可以用的过程。
百度在测试新的api。新的api有加密设置。因为上线时间太短，我还没抓到加密的过程。

**Comment by Kyle-Kyle** [comment]
百度已放弃新api。现在的wip branch可以正常下载。
