### ISSUE TITLE
严打结束。匿名下载可重新使用。无需登录。

### ISSUE THREAD

**Issue by Kyle-Kyle** [Kyle-Kyle/baidudl#82]
RT

**Comment by dwbclz** [comment]
棒棒哒。。。K大，心想事成~吉祥如意~新年快乐。

**Comment by srwgin** [comment]
商店版插件 还是要强制登陆 没更新吗

**Comment by Kyle-Kyle** [comment]
@srwgin 对。还没更新。昨天刚发现严打结束。还没来得及更新。晚上看一下。

**Comment by houshuheng** [comment]
商店有2个baidu-dl  哪个发布者是你上传的哦?

**Comment by Kyle-Kyle** [comment]
@houshuheng 中间有-的那个：baidu-dl

**Comment by iceJourney** [comment]
K大，发现又不能生成链接了，是已登录的状态
![snipaste_2018-02-07_16-51-48](https://user-images.githubusercontent.com/18734597/35906925-420bd966-0c27-11e8-8eda-cf305efe09c1.png)

**Comment by Kyle-Kyle** [comment]
我这个issue才刚发两天。我自己都不能用了..........baidu肯定有人关注了我的github....

**Comment by Kyle-Kyle** [comment]
爆炸。百度的api全改了。牛批.
