### ISSUE TITLE
Download using RPC? 

### ISSUE THREAD

**Issue by Piotrburz** [Kyle-Kyle/baidudl#83]
I've installed extension from here 
https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb/related?hl=en-GB
The slow download works, the high speed download works, but the speed is the same as with slow. I've tried this "RPC download" whatever it is, and it's not working, saying "Warning: aria2c is not running on http://localhost:6800/jsonrpc". What to do? Im on windows 10 btw.

**Comment by Kyle-Kyle** [comment]
you need to download a rpc server.
https://github.com/Kyle-Kyle/baidudl/tree/master/baidudl_rpc
after download the corresponding version, you can simply double click it

**Comment by Baytoro** [comment]
你好，请问一下，如果我想用远程服务器下载东西（实验室服务器166.XXX.XX.XX，平时要用户名密码ssh登录）。现在远程服务器上已经运行了aria2（enable了rpc），本地的rpc_server该如何填写呢。
http://166.XXX.XX.XX:6800/jsonrpc没法连接上啊，
![image](https://user-images.githubusercontent.com/25121365/48003221-cabbcb80-e148-11e8-9094-e85efcdd4938.png)
恳请大佬解答
