### ISSUE TITLE
免会员导出 VIP 下载链接

### ISSUE THREAD

**Issue by sarkdavidson** [Kyle-Kyle/baidudl#84]
- https://yqall02.baidupcs.com/file/
- https://allall01.baidupcs.com/file/
- https://allall02.baidupcs.com/file/
- http://nj02all01.baidupcs.com/file/

_（上面是有 VIP 直连的网址）_

* 使用大佬的 “直接下载” 提取了下载链接，将 http://d.pcs.baidu.com/file/ 替换为上述 VIP 直连 URL. 
* 100 兆电信网络，亲测 使用 http://nj02all01.baidupcs.com/file/  可以轻松达到 5 - 8 MB/s

补充：最大连接数不能超过 8，使用 128 线程版本的 aria2c 下载会服务端会自行切换成只有 8 线程下载；使用 Free Download Manager，`选项` - `通用` - `流量限制` - `最大连接数` 为 8，上下载速度无限制，可以保持稳定速度。

参考链接：https://github.com/acgotaku/BaiduExporter/issues/563

**Comment by iSteveyang** [comment]
https://pcs.baidu.com/rest/2.0/pcs/file?
这个是我的下载链接的开头,不一样啊

**Comment by Kyle-Kyle** [comment]
@iSteveyang 你这个链接我没见过可以下载的。
@sarkdavidson 最近百度方面在整改api。暂时不对插件做修改。

**Comment by yomorisan** [comment]
我看我网盘里的文件解析出来全是https://pcs.baidu.com/rest/2.0/pcs/file 开头的。
新上传的文件也都是这样。什么鬼？随机还是必然？

**Comment by yomorisan** [comment]
用雪月的插件解出来是上面那个。
1.4.2 的 baidudl解不出来，一直停留在 “ready. ”就没有然后了。
请问这是怎么回事？
<img width="121" alt="2018-03-07 11 13 56" src="https://user-images.githubusercontent.com/13185034/37100169-3f79f1d2-225d-11e8-9a4e-f5cd96d874b7.png">

**Comment by yomorisan** [comment]
用雪月的插件解出来是上面那个。
1.4.2 的 baidudl解不出来，一直停留在 “ready. ”就没有然后了。
请问这是怎么回事？
<img width="89" alt="2018-03-07 11 14 55" src="https://user-images.githubusercontent.com/13185034/37100243-64ce6828-225d-11e8-8fdc-a1eafc4076c5.png">

**Comment by lweo** [comment]
@Kyle-Kyle 这些链接失效了吗？替换后都是400响应。。

**Comment by Kyle-Kyle** [comment]
@lweo 是的。失效了。在百度更新api以后。master branch没有更新。可以用wip branch。目前只能在share page中使用。

**Comment by Kyle-Kyle** [comment]
目前在wip branch中开发。分享页面已可用，欢迎测试。

**Comment by lweo** [comment]
@Kyle-Kyle  测试了，只有Glink, 没有Hlink

**Comment by Kyle-Kyle** [comment]
@lweo 可能要等一下。目前hlink的生成比较慢。之后会想办法改善。

**Comment by lweo** [comment]
@Kyle-Kyle Glink就是普通下载链接吧？

**Comment by Kyle-Kyle** [comment]
@lweo 是的。

**Comment by Kyle-Kyle** [comment]
wip中已实现免会员到处下载链接。
