### ISSUE TITLE
非常感谢作者能出这么好用的插件，目前不能满速只能达到800k

### ISSUE THREAD

**Issue by kukudemajia** [Kyle-Kyle/baidudl#9]
比100K已经好很多了，要是能满速那就完美了，B.T.W:我是100M联通宽带
![qq 20170710155556](https://user-images.githubusercontent.com/17118600/28007871-bcfa5838-6587-11e7-99f2-fb4d78b62532.jpg)
![qq 20170710155607](https://user-images.githubusercontent.com/17118600/28007876-bf5db9d0-6587-11e7-8e99-820bdeecdb3f.jpg)

**Comment by Kyle-Kyle** [comment]
这个插件本身是不能满速的。最高速度应该是0.3*32M/s也就是10M/s左右。但是因为一些多线程的限制。一般在2~6M/s左右。800K/s的原因是IDM只能10线程下载。IDM调成32线程下载就可以在现在的基础上快3倍
