### ISSUE TITLE
linux中使用Glink得用什么下载工具……

### ISSUE THREAD

**Issue by AnestBlack** [Kyle-Kyle/baidudl#90]
尝试过wget下载失败……

创建了有几百b的文件后不能继续下载……

I try to use to WGET for download file ......

however,it failed while created hundreds bytes of file

**Comment by Kyle-Kyle** [comment]
其实可以使用wget的。但是有一些其他限制（跳转, user-agent）。
插件里面包含绕过限制的代码。
可以生成hlink以后用baidudl_rpc下载（其实就是aria2的--enable-rpc选项）。

**Comment by AnestBlack** [comment]
没有在wip中找的你的2.0版本……

以及linux上似乎并不能使用浏览器插件的样子……

(目前是打算用win10给linux传脚本运行，然后再用linux给win10传文件

**Comment by Kyle-Kyle** [comment]
wip branch: https://github.com/Kyle-Kyle/baidudl/tree/wip

1. linux上可以使用浏览器插件。可能你的设置有问题。
2.你想把文件存在哪台机器上（叫a），就在那台机器a上上运行aria2c的server，然后在插件中把rpc server设置成对应的server。这样就能在任意机器(叫b)上下载文件到a上。如果需要的话。还可以在插件中可以设置密码。

**Comment by AnestBlack** [comment]
wip branch我找到了，但是没有发现里面有“2.0”的下载……rpc里面有个py2的文件用来运行server的

或许我应该先装个图形界面……

**Comment by Kyle-Kyle** [comment]
......因为还没写完。所以没有发布。。请自行clone然后checkout。。运行server 直接使用command aria2c --enable-rpc....
不需要图形界面。。

**Comment by AnestBlack** [comment]
![1523370100010](https://user-images.githubusercontent.com/32736719/38562823-092c2016-3d0e-11e8-8a13-c8e4be208138.jpg)
clone了一份后在linux中似乎无法运行……

py2的那个文件我也丢进去了，似乎no found，和aria2c是一个文件夹（上传图片时的测试，未在图中...

**Comment by Kyle-Kyle** [comment]
....因为aria2c.exe是windows文件。。。
apt-get install aria2
aria2c --enable-rpc

**Comment by Kyle-Kyle** [comment]
我没有打包linux版本的aria2。。因为默认会用linux的人都会装aria2。。。

**Comment by AnestBlack** [comment]
会装……但是不会用……或许明天你有空的话，即时聊天工具上来指导一下吗

我把号码发你邮箱上(笑哭

**Comment by Kyle-Kyle** [comment]
行啊。也许时候写个详细教程了...
