### ISSUE TITLE
在個人主頁中無法使用

### ISSUE THREAD

**Issue by unblockiqiyi** [Kyle-Kyle/baidudl#92]
使用的是1.4.2版。
我先選取要下載的檔案，之後點選baidudl的圖標只出現Ready，過了幾秒後網頁會自動重新載入，沒有產生下載連結。

**Comment by Kyle-Kyle** [comment]
github中已更新。

**Comment by AggiWang** [comment]
我的也是，用不了，今天刚下载的，还是用不了，一直是ready并跳转到百度云盘主页

**Comment by unblockiqiyi** [comment]
@Kyle-Kyle 我使用的就是github的最新版，刪除重弄後還是碰到同樣問題。

**Comment by Kyle-Kyle** [comment]
已更新
