### ISSUE TITLE
hilink都获取不到了啊

### ISSUE THREAD

**Issue by qwertccc** [Kyle-Kyle/baidudl#93]
我用的那个额最新的wip分支的

**Comment by qwertccc** [comment]
然后再home这个目录下，glink也获取不到

**Comment by Kyle-Kyle** [comment]
wip branch目前只支持分享页面。完成主页面的部分后就会覆盖master branch

**Comment by qwertccc** [comment]
分享页面获取不到hlink，只有glink

**Comment by Kyle-Kyle** [comment]
请问目录下文件多吗。现在hlink出现要等一会儿

**Comment by Kyle-Kyle** [comment]
已确认。baidu更新了api。

**Comment by Kyle-Kyle** [comment]
wip branch已覆盖master branch
