### ISSUE TITLE
点击灯泡时不断刷新网盘页面

### ISSUE THREAD

**Issue by 25890** [Kyle-Kyle/baidudl#95]
打开网盘列表，勾选相关文件，点击灯泡，就直接刷新网盘页面，而且还是不断刷新

**Comment by stan1233** [comment]
一样一样，坐等更新

**Comment by Kyle-Kyle** [comment]
https://chrome.google.com/webstore/detail/baidu-dl/lflnkcmjnhfedgibjackiibmcdnnoadb?hl=en-GB
已更新
