### ISSUE TITLE
Glink和Hlink都是什么意思呢

### ISSUE THREAD

**Issue by Tracis** [Kyle-Kyle/baidudl#97]

**Comment by JrantKing** [comment]
HLink好像下载不了

**Comment by wonder566** [comment]
那么就是说hlink是无关用户的地址？为什么用本地的aria2rpc可以下载用vps上的就提示  HTTP response header was bad or unexpected

**Comment by wonder566** [comment]
@Kyle-Kyle 本地用aria2很快，但我有个vps（https连接并且设置了token），想离线下载，baidudl我没找到怎么添加有token的地址

**Comment by Kyle-Kyle** [comment]
@wonder566 在options页面可以设置所有rpc相关的信息。

**Comment by wonder566** [comment]
@Kyle-Kyle 我在这里没找到设置secret token和ssl之类的选项

**Comment by wonder566** [comment]
@Kyle-Kyle 找到了，得去掉overflow: scroll;这个。另外还有个小问题，chrome store里安装的插件可以选择rpc服务器，手动安装的这个2.0版本就不能选择了，我只能把默认的删掉只留新添加的一个服务器才能正确连接上

**Comment by Kyle-Kyle** [comment]
@wonder566 嗯对。这个部分还没完成。
另外。你这个options界面看起来有点奇怪啊。可能需要再更新一下。
